import test from 'node:test';import assert from 'node:assert/strict';
import {laboratory,visible,turn,positionOf,initial,retrieve} from '../lib/game/engine.mjs';
import {findPath,clearSegment,advancePose,animationCell,facing} from '../lib/game/navigation.mjs';
import VISUALS from '../data/character-visuals.json' with {type:'json'};
test('實驗場是獨立世界線，不修改入門初始世界',()=>{const normal=initial('normal'),lab=laboratory('lab');assert.equal(normal.player.location,'gate');assert.equal(normal.enrolled,false);assert.equal(lab.player.location,'home');assert.equal(visible(lab).npcs.length,1);assert.equal(visible(lab).npcs[0].id,'shen');assert.equal(lab.events[0].timeline,'lab');});
test('實驗場 NPC 固定站位，玩家與目擊判定一致',()=>{const a=laboratory('lab');const p=positionOf(a,'shen');assert.deepEqual(p,visible(a).npcs[0].position);const b=turn(a,{id:'tick',revision:0,action:{type:'wait',minutes:5}});assert.deepEqual(positionOf(b,'shen'),p);assert.deepEqual(positionOf(JSON.parse(JSON.stringify(b)),'shen'),visible(b).npcs[0].position);});
test('尋路繞過障礙，所有分段都可通行且小於回合步長',()=>{const start={x:-25,z:-13},goal={x:-5,z:-13};const path=findPath(start,goal);assert.ok(path.length>1);let prev=start;for(const p of path){assert.ok(clearSegment(prev,p));assert.ok(Math.hypot(p.x-prev.x,p.z-prev.z)<=7.001);prev=p;}assert.deepEqual(path.at(-1),goal);});
test('尋路每一步通過正式引擎並持久保存',()=>{let s=laboratory('walking');const path=findPath(s.player.position,{x:-6,z:2});for(const [i,p] of path.entries())s=turn(s,{id:'walk'+i,revision:s.revision,action:{type:'walk',position:p}});const before=s.revision;s=turn(s,{id:'speak',revision:s.revision,action:{type:'speech',target:'shen',text:'師父，記得實驗嗎？'}});assert.equal(s.revision,before+1);assert.ok(s.events.at(-1).knowers.includes('shen'));});
test('固定速度插值不超越目標；方向與素材列對應',()=>{const p=advancePose({x:0,z:0},{x:3,z:4},.1,10);assert.ok(Math.abs(Math.hypot(p.x,p.z)-1)<1e-8);assert.deepEqual(advancePose({x:0,z:0},{x:3,z:4},10,10),{x:3,z:4,walk:true});assert.equal(facing(-3,3),1);assert.equal(facing(3,-3),2);assert.equal(facing(-3,-3),3);assert.equal(facing(3,3),0);const profile={...VISUALS.atlas,...VISUALS.profiles.shen};assert.deepEqual(animationCell(profile,2,true,.2),{column:2,row:5});assert.deepEqual(animationCell(profile,0,false,10),{column:0,row:4});});

test("實驗場重要共同記憶在百回合後仍可靠檢索",()=>{let s=laboratory("longlab");for(let i=0;i<100;i++)s=turn(s,{id:"wait"+i,revision:s.revision,action:{type:"wait",minutes:1}});assert.ok(retrieve(s,"shen").some(e=>e.type==="experiment"));});
