import test from 'node:test';
import assert from 'node:assert/strict';
import {initialStory,record,advanceStory,playerView,resolveAction} from '../lib/story/world.mjs';
import {validateDossier,sealLiving,assertLivingSeals,check,livingActions,interveneLiving,livingKnown,canPlan} from '../lib/story/living-world.mjs';
import {isolatedEventContext,prepareScene} from '../lib/story/scene.mjs';
const dossier=()=>({title:'劍架修整',cause:'顧長青從此刻開始安排器具修整。',closure:'校對結束後收束，不論是否完成。',hook:{place:'home',text:'庭院貼出器具校對的安排。'},actors:[{id:'gu',motive:'完成自己負責的維護',goal:'核對兩批器具'}],facts:[{id:'tools',text:'本次器具需要重新核對。',knowers:['gu']},{id:'ledger',text:'第二份核對表放在藏經樓。',knowers:['gu']}],evidence:[{id:'register',fact:'ledger',place:'home',after:0,expires:6000,difficulty:0}],beliefs:[{actor:'gu',claim:'可能是潮氣影響木材。',basis:'tools',status:'suspected'}],steps:[{after:120,actor:'gu',place:'home',activity:'維護器具',difficulty:30,success:'初次核對完成。',failure:'初次核對未能完成。',public:false,peer:'jiang'},{after:2880,actor:'gu',place:'home',activity:'器具交接',difficulty:30,success:'器具交接完成。',failure:'本次交接受阻，工作告一段落。',public:true,peer:null}]});
function state(){const s=initialStory('test');sealLiving(s,dossier(),record);return s;}
test('old save upgrade retains state and does not import another worldline',()=>{const s=initialStory('old');s.player.realm='聚氣圓滿';s.player.health=47;s.player.items.木劍=2;const original=JSON.stringify(s.truth);sealLiving(s,dossier(),record);assert.equal(s.player.health,47);assert.equal(s.player.items.木劍,2);assert.equal(s.player.realm,'聚氣圓滿');assert.equal(JSON.stringify(s.truth),original)});
test('fixed truth rejects mutation while legitimate future effects remain mutable',()=>{const s=state();s.living.events[0].influence=12;assert.doesNotThrow(()=>assertLivingSeals(s));s.living.events[0].dossier.cause='改成玩家猜測';assert.throws(()=>assertLivingSeals(s),/封存/)});
test('unattended event closes with private results and quiet period',()=>{const s=state();s.player.location='room';const frozen=JSON.stringify(s.living.events[0].dossier);advanceStory(s,3000);const e=s.living.events[0];assert.equal(e.status,'closed');assert.equal(e.actual.length,2);assert.equal(JSON.stringify(e.dossier),frozen);assert.equal(canPlan(s),false);assert.ok(s.events.filter(e=>e.type==='autonomous-action').every(e=>!e.knowers.includes('player')))});
test('private truths and current remote locations never enter player projection',()=>{const s=state();s.npcs.gu.location='library';const view=playerView(s);assert.equal(view.living,undefined);assert.equal(view.truth,undefined);assert.ok(!JSON.stringify(view).includes('第二份核對表'));assert.notEqual(view.locator.find(n=>n.id==='gu')?.location,'library')});
test('private speaker gets own knowledge, other NPCs do not',()=>{const s=state();assert.equal(livingKnown(s,['shen']).length,0);assert.equal(livingKnown(s,['gu']).length,2);const c=isolatedEventContext(s,'gu',s.events,s.messages);assert.deepEqual(c.actors.map(n=>n.id),['gu']);assert.ok(c.sharedMemories.some(e=>e.content.includes('第二份核對表')));assert.equal(isolatedEventContext(s,'shen',s.events,s.messages),null)});
test('event validator rejects guessed identities and unsupported belief sources',()=>{const d=dossier();d.beliefs[0].actor='shen';assert.throws(()=>validateDossier(d),/本人已知/);d.beliefs=[];d.steps[0].actor='outsider';assert.throws(()=>validateDossier(d),/行動者/)});
test('evidence rolls are persisted, bounded and cannot be spammed',()=>{const s=state();const a=livingActions(s).find(a=>a.operation==='investigate');interveneLiving(s,a,record);assert.equal(livingActions(s).filter(a=>a.operation==='investigate').length,0);assert.equal(s.living.events[0].interventions.length,1);assert.throws(()=>interveneLiving(s,a,record));const fixed=s.seed;const t=structuredClone(s);assert.deepEqual(check(s,{opponent:'shen'}),check(t,{opponent:'shen'}));assert.equal(check(s,{opponent:'shen'}).chance,0);assert.notEqual(s.seed,fixed)});
test('continue alone moves the clock without inventing dialogue or decisions',()=>{const s=initialStory('alone');s.player.location='room';const r=resolveAction(s,{kind:'continue'},'繼續');assert.ok(r.state.time>s.time);assert.equal(r.state.player.location,'room');assert.ok(r.state.messages.every(m=>m.speaker==='narrator'))});
test('AI director sees no player guess; event is sealed before NPC narrative',async()=>{const s=initialStory('director');let calls=0;const result=await prepareScene({state:s,text:'我猜師父是主謀',action:{kind:'speak'},target:'shen',connection:{provider:'test',model:'test'},enableLiving:true,generate:async(c,p,input)=>{calls++;if(p.includes('你只建立後台事件檔')){assert.ok(!JSON.stringify(input).includes('我猜'));return dossier();}return{beats:[{speaker:'shen',text:'你是從哪裡得知的？',memoryRefs:[],turnToPlayer:true}],openQuestion:null,stopReason:'decision'};}});assert.equal(calls,2);assert.equal(result.state.living.events.length,1);assert.equal(result.state.living.events[0].dossier.cause,dossier().cause)});
const {settleClock}=await import('../lib/story/world-clock.mjs');
test('offline settlement is idempotent, preserves truth and catches up private plans',()=>{const s=state();s.clock={anchor:1000,rate:1};s.player.location='room';const end=1000+3000*60000;let r=settleClock(s,end);assert.equal(r.elapsed,1440);r=settleClock(r.state,end);r=settleClock(r.state,end);assert.equal(r.state.living.events[0].status,'closed');assert.equal(settleClock(r.state,end).changed,false);assert.ok(!playerView(r.state).messages.some(m=>m.content==='初次核對完成。'))});
test('legacy world clock starts now rather than retroactively aging the save',()=>{const s=initialStory('legacy');const r=settleClock(s,999999999999);assert.equal(r.elapsed,0);assert.equal(r.state.time,s.time);assert.equal(r.state.player.health,s.player.health)});
