import {test} from 'node:test';import assert from 'node:assert/strict';import {initial,turn,branch,visible,route,parse,advance} from '../lib/game/engine.mjs';import {generateArea} from '../lib/game/spatial.mjs';
let seq=0;const act=(s,a)=>turn(s,{id:`3d-${++seq}`,revision:s.revision,action:a});
test('行走保存座標、時間、回合；重試不重走',()=>{const s=initial('spatial'),req={id:'walk1',revision:0,action:{type:'walk',position:{x:0,z:6}}};const n=turn(s,req);assert.deepEqual(n.player.position,{x:0,z:6});assert.equal(n.time,481);assert.deepEqual(turn(n,req),n);assert.deepEqual(s.player.position,{x:0,z:10})});
test('邊界、障礙和穿牆被伺服器拒絕',()=>{const s=initial('x');assert.throws(()=>act(s,{type:'walk',position:{x:100,z:10}}));s.player.position={x:-15,z:-3};assert.throws(()=>act(s,{type:'walk',position:{x:-15,z:-18}}));assert.throws(()=>act(s,{type:'walk',position:{x:Infinity,z:3}}))});
test('遠處不能向指定 NPC 交談',()=>{let s=initial('x');s.player.position={x:30,z:30};assert.throws(()=>act(s,{type:'speech',target:'shen',text:'你好'}));s.player.position={x:-6,z:2};const n=act(s,{type:'speech',target:'shen',text:'你好'});assert(n.events.at(-1).knowers.includes('shen'))});
test('新地圖和新人生成後持久保存且不重複建立',()=>{let s=initial('x');s.player.location='home';s=act(s,{type:'explore'});const copy=JSON.parse(JSON.stringify(s));s=act(s,{type:'explore'});assert.deepEqual(s.generatedPlaces,copy.generatedPlaces);assert.deepEqual(s.generatedNPCs,copy.generatedNPCs);assert.equal(s.generatedEdges.length,1);assert.equal(route('home','grove',s).minutes,12);const b=branch(copy,'branch');assert.deepEqual(b.generatedNPCs,copy.generatedNPCs);assert.equal(initial('fresh').generatedPlaces.grove,undefined)});
test('新角色按作息旅行，初次相遇保存介紹記憶',()=>{let s=initial('x');s.player.location='home';s=act(s,{type:'explore'});s=act(s,{type:'move',target:'grove'});assert.equal(visible(s).npcs[0].id,'newcomer');s=act(s,{type:'speech',target:'newcomer',text:'你叫什麼？'});assert(s.events.some(e=>e.type==='meet'));const before=JSON.stringify(s.generatedNPCs);s.time=1079;advance(s,1);assert.equal(s.npcs.newcomer.travel.to,'home');advance(s,12);assert.equal(s.npcs.newcomer.location,'home');assert.equal(JSON.stringify(s.generatedNPCs),before)});
test('自然語言可以指向已生成地名',()=>{const s=initial('x');s.generatedPlaces.grove=generateArea('x').place;assert.deepEqual(parse(`去${s.generatedPlaces.grove.name}`,s),{type:'move',target:'grove'})});
test('舊存檔缺少場景座標仍可升級並行走',()=>{const s=initial('legacy');delete s.player.position;delete s.generatedPlaces;delete s.generatedNPCs;delete s.generatedEdges;const n=act(s,{type:'walk',position:{x:0,z:6}});assert.deepEqual(n.player.position,{x:0,z:6});assert.deepEqual(n.generatedPlaces,{})});
