// @ts-nocheck
'use client';
import {useState} from 'react';
import {TRAITS,CONTEXTS} from '../lib/story/personality.mjs';
const labels={trust:'信任',respect:'尊重',closeness:'親近',caution:'戒備',interest:'利益一致',grievance:'恩怨'};
export default function DeveloperPanel({data,world,busy,onSelect,onEdit}){const [tab,setTab]=useState('shen'),[note,setNote]=useState('');const c=data?.characters?.find(c=>c.id===tab);if(!data)return <p>正在讀取開發者資料…</p>;return <><p className="developer-notice">開發者專用 · 此處包含角色內在狀態。這些資料不會自動成為洛河或其他 NPC 的知識。</p><div className="story-tabs">{[['player','洛河 · 成長'],...data.characters.map(c=>[c.id,c.name]),['generation','生成依據']].map(([id,name])=><button key={id} className={tab===id?'active':''} disabled={busy} onClick={()=>{setTab(id);if(id!=='generation')onSelect(id)}}>{name}</button>)}</div>
{tab==='player'&&<><h3>個性不是預設答案</h3><p>僅從玩家親自輸入的原句建立觀察。AI 補寫台詞不計入證據；相同原句不重複累積。三筆不同來源後才視為漸漸形成，仍可修正。</p>{data.personality.traits.length?data.personality.traits.map(t=><article className="developer-trait" key={t.id}><h3>{t.label} <small>{CONTEXTS[t.context]} · {({observed:'觀察中',emerging:'漸漸形成',confirmed:'已確認',dismissed:'已排除'})[t.status]}</small></h3>{t.evidence.map(e=><blockquote key={e.message}><p>「{e.quote}」</p><small>玩家親自輸入 · 第 {Math.floor(e.time/1440)+1} 日 · {e.message}</small></blockquote>)}<div className="story-tabs"><button disabled={busy||t.status==='confirmed'} onClick={()=>onEdit({operation:'confirm',trait:t.id})}>確認此傾向</button><button disabled={busy||t.status==='dismissed'} onClick={()=>onEdit({operation:'dismiss',trait:t.id})}>不符合角色，排除</button></div></article>):<p>尚無足夠個性證據。主角演出保持中性。</p>}<h3>補充這條世界線的演出設定</h3><p><small>例如：「面對熟人會開玩笑，但不能替我答應重要事情。」只補充日常口吻，不設定新能力或過去事件。</small></p><textarea className="developer-note" value={note} maxLength={240} onChange={e=>setNote(e.target.value)} placeholder="可留白，讓個性隨遊玩形成…"/><button className="story-primary" disabled={busy||!note.trim()} onClick={()=>{onEdit({operation:'note',text:note});setNote('')}}>保存演出補充</button>{data.personality.notes.filter(n=>n.active).map(n=><div className="story-setting-row" key={n.id}><span>{n.text}</span><button disabled={busy} onClick={()=>onEdit({operation:'remove-note',note:n.id})}>停用</button></div>)}<small>每次修改保留事件紀錄。這裡不會改寫已說過的話。</small></>}
{c&&<><h3>{c.name} · 原生人格</h3><p>{c.original.personality}</p><dl className="developer-facts"><dt>說話習慣</dt><dd>{c.original.voice}</dd><dt>自身目標</dt><dd>{c.original.goal}</dd><dt>價值觀</dt><dd>{c.original.values.join('；')}</dd><dt>底線</dt><dd>{c.original.boundaries?.join('；')}</dd><dt>行為習慣</dt><dd>{c.original.habits?.join('；')}</dd><dt>避免失真</dt><dd>{c.original.avoid?.join('；')}</dd></dl><small>{c.original.sourceNote}</small><h3>這條世界線的目前狀態</h3><div className="story-stat-grid"><div><small>所在地</small><strong>{c.current.travel?`前往${world.places[c.current.travel.to]?.name}`:world.places[c.current.location]?.name}</strong></div><div><small>目前活動</small><strong>{c.current.activity}</strong></div><div><small>修為 / 修行時數</small><strong>{c.current.realm}</strong><small>{c.current.trainingHours.toFixed(1)} 小時</small></div><div><small>情緒 / 疲勞</small><strong>{c.current.emotionalState}</strong><small>疲勞 {Math.round(c.current.fatigue)} · 健康 {Math.round(c.current.health)}</small></div></div><h3>對洛河的判斷</h3><div className="developer-relations">{Object.entries(c.current.relations).map(([k,v])=><span key={k}>{labels[k]} <b>{Number(v).toFixed(1)}</b></span>)}</div><p>履約 {c.current.reliability.kept} 次 · 已知失約 {c.current.reliability.broken} 次</p><details><summary>關係變化的事件依據（最近 {c.current.judgement.length} 筆）</summary>{c.current.judgement.map((j,i)=><p key={i}><small>{j.event}</small><br/>{Object.entries(j.changes).map(([k,v])=>`${labels[k]} ${Number(v)>0?'+':''}${Number(v).toFixed(1)}`).join('；')}</p>)}</details><details><summary>每日行程與成長條件</summary>{c.original.daily.map(([h,p,a])=><p key={h}>{h}:00 · {world.places[p]?.name} · {a}</p>)}<p>下一階段：{c.original.nextRealm}<br/>修行門檻 {c.original.threshold} 小時 · 準備靈石 {c.original.breakthroughCost}，另需經驗與身體狀態達標。</p></details><h3>此人真正知道的事件</h3>{data.selectedActor===tab?data.actorMemories.map(e=><article className="developer-memory" key={e.id}><p>{e.content}</p><small>{e.source} · 第 {Math.floor(e.time/1440)+1} 日 · {e.id}</small></article>):<p>正在讀取個體記憶…</p>}</>}
{tab==='generation'&&<><h3>最近一次實際生成依據</h3><p>這是送給模型的可見資料與引擎處理結果，不是模型內部思考。多人場景只提供共同知情的事件；導航位置不加入敘事上下文。</p>{data.lastGeneration?<><p>{data.lastGeneration.provider} / {data.lastGeneration.model} · 第 {data.lastGeneration.revision} 回合</p><pre className="developer-json">{JSON.stringify(data.lastGeneration,null,2)}</pre></>:<p>此世界線尚未產生新版場景回應。</p>}</>}
</>}
