// @ts-nocheck
'use client';
import {useState,useEffect,useRef} from 'react';
import {BookOpen,Map,Clock,Users,Settings,Save,Send,ChevronDown,ArrowLeft,Feather,Compass,X,Leaf,ScrollText,Heart,Sun,Plus,RefreshCw,Maximize2} from 'lucide-react';
import {route} from '../lib/game/engine.mjs';
import DeveloperPanel from './developer-panel';
import ART from '../data/art-v2.json';
import {playbackMessages,currentPerformance,portraitSource,EXPRESSION_LABELS} from '../lib/story/performance.mjs';
const names={player:'洛河',narrator:'山中光陰',shen:'沈滄月',yan:'晏清辭',jiang:'江離',gu:'顧長青'};
const day=t=>`第 ${Math.floor(t/1440)+1} 日 · ${String(Math.floor(t%1440/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
const seasons=['春','夏','秋','冬'];
async function api(body,url='/api/story'){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(95000)});const data=await r.json();if(!r.ok){const e=new Error(data.error||'請求失敗');Object.assign(e,data);throw e;}return data;}
function Portrait({id='shen',expression='calm',className=''}){return <div aria-label={names[id]+'人物立繪'} className={`story-portrait unified-portrait ${className}`} style={{backgroundImage:`url(${portraitSource(ART,id,expression)})`,backgroundSize:'contain',backgroundPosition:'center bottom',backgroundRepeat:'no-repeat'}}/>;}
export default function StoryGame(){
 const [list,setList]=useState({worlds:[],saves:[],configured:{}}),[world,setWorld]=useState(null),[busy,setBusy]=useState(false),[boot,setBoot]=useState(true),[signin,setSignin]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[modal,setModal]=useState(null),[text,setText]=useState(''),[target,setTarget]=useState('shen'),[pending,setPending]=useState(null),[provider,setProvider]=useState('openai'),[model,setModel]=useState(''),[key,setKey]=useState(''),[models,setModels]=useState([]),[connection,setConnection]=useState(null),[search,setSearch]=useState(''),[events,setEvents]=useState([]),[category,setCategory]=useState('all'),[detail,setDetail]=useState(null),[newName,setNewName]=useState('棲風峰 · 初識'),[minutes,setMinutes]=useState(60),[training,setTraining]=useState(false),[promiseKind,setPromiseKind]=useState('train'),[promisePlace,setPromisePlace]=useState('court'),[promiseHours,setPromiseHours]=useState(24),[promiseTraining,setPromiseTraining]=useState(60),[older,setOlder]=useState(true);
 const [visibleThrough,setVisibleThrough]=useState(null);
 const [developerData,setDeveloperData]=useState(null),[mapPlace,setMapPlace]=useState(null);
 async function loadDeveloper(actor='shen'){const d=await api({op:'developer',world:world.id,actor});setDeveloperData(d);}
 const scroll=useRef(null),bottom=useRef(null),autoScroll=useRef(true),input=useRef(null),modalRef=useRef(null),priorFocus=useRef(null);
 const ready=!!model&&(!!key||list.configured[provider]);
 async function refreshList(){const d=await api({op:'list'});setList(d);return d;}
 useEffect(()=>{refreshList().catch(e=>{setError(e.message);setSignin(!!e.signin)}).finally(()=>setBoot(false));try{setProvider(localStorage.getItem('wendao-provider')||'openai');setModel(localStorage.getItem('wendao-model')||'')}catch{}},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{if(autoScroll.current)bottom.current?.scrollIntoView({behavior:'smooth',block:'end'})},[world?.messages?.length,visibleThrough,busy]);
 useEffect(()=>{if(!modal)return;priorFocus.current=document.activeElement;modalRef.current?.focus();const onKey=e=>{if(e.key==='Escape'){setModal(null);return}if(e.key==='Tab'){const items=[...modalRef.current.querySelectorAll('button:not(:disabled),a[href],input,textarea,select,[tabindex="0"]')];if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);priorFocus.current?.focus?.()}},[modal]);
 async function run(fn){if(busy)return;setBusy(true);setError('');try{return await fn()}catch(e){setError(e.name==='TimeoutError'?'連線等待逾時。請用原回合重試，避免重複操作。':e.message);if(e.signin)setSignin(true)}finally{setBusy(false)}}
 function accept(d,animate=false){const previous=world?.id===d.id?Math.max(0,...world.messages.map(m=>m.seq)):0;const fresh=d.messages.filter(m=>m.seq>previous);setVisibleThrough(animate&&fresh.length>1?fresh[0].seq:null);setWorld(d);setTarget(d.npcs.some(n=>n.id===target)?target:d.scene.target||d.npcs[0]?.id||null);setOlder(d.messages.length>=60);}
 async function openWorld(id){await run(async()=>{accept(await api({op:'load',world:id}));setPending(null);setText('');setModal(null);autoScroll.current=true})}
 async function newWorld(){await run(async()=>{accept(await api({op:'new',name:newName}));setPending(null);setModal(null);await refreshList()})}
 async function turn(action=null,retry=false,overrideText=null){if(!world||busy)return;const value=overrideText??text;if(!action&&!value.trim()&&!retry)return;const request=retry?pending:{op:'turn',world:world.id,revision:world.revision,requestId:crypto.randomUUID(),text:action?'':value,action,target,provider,model};if(!request)return;if(retry&&request.provider!==provider){setError('請切回原本的 AI Provider 後重試，或重新載入核對。');return;}setPending(request);autoScroll.current=true;await run(async()=>{const d=await api({...request,sessionKey:key});accept(d,true);setPending(null);if(!action)setText('');if(request.action?.kind==='personality-edit'){await loadDeveloper('player')}else{setModal(null);input.current?.focus()}});}
 async function memory(q=search){await run(async()=>{const d=await api({op:'memory',world:world.id,q});setEvents(d.events);setDetail(null)})}
 async function openModal(m){setModal(m);setError('');if(m==='memory')await memory();if(m==='save')await run(refreshList);if(m==='developer')await run(()=>loadDeveloper());if(m==='map')setMapPlace(world.player.location)}
 async function save(){await run(async()=>{await api({op:'save',world:world.id});await refreshList();setToast('這一刻的世界與對話已存檔。')})}
 async function branch(saveId=null){await run(async()=>{accept(await api({op:saveId?'restore':'branch',world:world.id,save:saveId,name:saveId?'歷史回聲 · 分支':'另一種可能 · 分支'}));await refreshList();setPending(null);setModal(null);setToast('已建立獨立分支，原世界線保留。')})}
 async function testAI(){await run(async()=>{const d=await api({op:'test',provider,model,sessionKey:key},'/api/ai');setConnection(d);setModels(d.models||[]);try{localStorage.setItem('wendao-provider',provider);localStorage.setItem('wendao-model',model)}catch{}})}
 const selected=world?.npcs.find(n=>n.id===target),time=world?.time||0;
 const shown=playbackMessages(world?.messages||[],visibleThrough),unread=(world?.messages.length||0)-shown.length,performance=currentPerformance(shown,target),portraitId=performance.speaker;
 function nextBeat(){setVisibleThrough(current=>world.messages.find(m=>m.seq>(current??Infinity))?.seq??null);}
 function joinIn(){setVisibleThrough(null);input.current?.focus();}
 const filtered=events.filter(e=>category==='all'||(category==='promise'?e.type.startsWith('promise'):category==='important'?['enroll','promise','promise-fulfilled','promise-missed','news','growth-observed','personal-memory'].includes(e.type):category==='speech'?e.type==='speech':e.type!=='speech'));
 const nav=[['memory',BookOpen,'記憶'],['character',Leaf,'自身'],['people',Users,'人物'],['map',Compass,'山河'],['time',Clock,'光陰'],['save',Save,'世界線']];
 return <main className={`story-root ${world?'story-active':'story-entry'}`}>
 {!world?<><div className="story-entry-art"/><div className="story-entry-title"><small>WEN DAO JIU ZHOU</small><h1>問道九州</h1><p>山河自有歲月<br/>而你，會被記得。</p><span>沉浸式對話 · 棲風峰實驗場</span></div><section className="story-entry-panel"><div className="story-kicker">一盞茶，一段未完的故事</div><h2>重返山中</h2><p>有人正在等一封信，有人已動身遠行。<br/>在此生活，留下屬於你的痕跡。</p>{boot?<p>正在讀取世界線…</p>:signin?<a className="story-primary" href="/signin-with-chatgpt?return_to=%2F">登入並繼續</a>:<><label>新世界線名稱<input value={newName} maxLength={60} onChange={e=>setNewName(e.target.value)}/></label><button className="story-primary" onClick={newWorld} disabled={busy}><Plus size={16}/> 開始在棲風峰生活</button><div className="story-worlds">{list.worlds.map(w=><button key={w.id} onClick={()=>openWorld(w.id)} disabled={busy}><span>{w.name}<small>已走過 {w.revision} 個回合</small></span><span>繼續 →</span></button>)}</div><button className="story-text-button" onClick={()=>setModal('settings')}><Settings size={15}/> AI 連線設定</button></>}<small>世界保存在帳號下。AI 連線需另行設定。<br/>舊版操作實驗仍保留於 <a href="/legacy">先前版本</a>。</small></section></>:<>
 <section className="story-scene" aria-label="目前場景"><div className={`story-scene-art place-${world.player.location}`} style={{backgroundImage:`url(${ART.scenes[world.player.location]})`}}/><div className="story-scene-shade"/><div className="story-mist"/><header className="story-location"><button aria-label="返回世界線選擇" onClick={()=>{setWorld(null);setPending(null);refreshList().catch(e=>setError(e.message))}} disabled={busy}><ArrowLeft size={17}/></button><div><small>太虛宗 · 人間一隅</small><h1>{world.places[world.player.location].name}</h1></div></header><div className="story-time"><Sun size={16}/><span>{day(time)}<small>{seasons[Math.floor(time/129600)%4]} · 靜候你接話時，時間暫歇</small></span></div>
 {portraitId&&<Portrait id={portraitId} expression={performance.expression} className="story-hero"/>}<div className="story-scene-caption"><span className="story-kicker">{portraitId?'此刻的發言者':'山中無人語'}</span><h2>{names[portraitId]||'獨處片刻'}<small>{performance.delivery||EXPRESSION_LABELS[performance.expression]}</small></h2><p>{world.places[world.player.location].description}</p><div className="story-present">{world.npcs.map(n=><button key={n.id} className={target===n.id?'active':''} onClick={()=>setTarget(n.id)} disabled={busy||!!pending}>{n.name}<small>{target===n.id?'正在交談':'也在此處'}</small></button>)}</div></div>
 <nav className="story-nav" aria-label="世界功能">{nav.map(([id,Icon,label])=><button key={id} onClick={()=>openModal(id)} disabled={busy}><Icon size={21}/><span>{label}</span></button>)}</nav></section>
 <section className="story-conversation" aria-label="連續對話"><header className="story-dialogue-heading"><div><span className="story-kicker">此間 · 故事繼續</span><h2>{selected?`與${selected.name}交談`:'聽見山中的光陰'}</h2></div><div className="story-heading-tools">{list.isDeveloper&&<button aria-label="開發者檢視" title="開發者檢視" onClick={()=>openModal('developer')}>〈/〉</button>}<button title="設定" aria-label="設定" onClick={()=>openModal('settings')}><Settings size={19}/></button></div></header><div className="story-transcript" ref={scroll} onScroll={()=>{const e=scroll.current;autoScroll.current=e.scrollHeight-e.scrollTop-e.clientHeight<100}}>
 {older&&<button className="story-older" disabled={busy} onClick={()=>run(async()=>{const d=await api({op:'messages',world:world.id,before:world.messages[0]?.seq});autoScroll.current=false;setWorld({...world,messages:[...d.messages,...world.messages]});setOlder(d.messages.length===60)})}>翻閱更早的對話</button>}
 {shown.map((m,i)=><div key={m.id} className={`story-message ${m.speaker==='narrator'?'narration':m.speaker==='player'?'player-message':'npc-message'} ${m.kind==='thought'?'thought':''}`}>{(i===0||Math.floor(shown[i-1].minute/1440)!==Math.floor(m.minute/1440))&&<div className="story-day-divider">{day(m.minute)}</div>}{m.speaker!=='narrator'&&<div className="story-speaker"><span>{names[m.speaker]||m.speaker}</span>{m.performance?.to&&<small>對{m.performance.to==='all'?'在場眾人':names[m.performance.to]}</small>}{m.kind!=='thought'&&<button className="story-pin" title="保留為重要記憶" aria-label="保留這句話為重要記憶" disabled={busy||!!pending} onClick={()=>turn({kind:'remember',message:m.id})}><BookOpen size={12}/></button>}<small>{m.kind==='thought'?'未說出口':m.kind==='promise'?'許下承諾':m.kind==='auto-dialogue'?'日常補寫':`${String(Math.floor(m.minute%1440/60)).padStart(2,'0')}:${String(Math.floor(m.minute%60)).padStart(2,'0')}`}</small></div>}<p>{m.content}</p>{m.performance?.delivery&&<small className="story-delivery">{m.performance.delivery}</small>}</div>)}{busy&&<div className="story-thinking"><span/>正在整理這一刻的因果…</div>}<div ref={bottom}/></div>
 <div className="story-compose">{unread>0&&<div className="story-playback" role="status"><span>本段已保存 · 還有 {unread} 段</span><button onClick={nextBeat}>下一段</button><button onClick={joinIn}>展開本段並接話</button></div>}{!unread&&world.scene.stopReason==='decision'&&<p className="story-decision">{world.scene.openQuestion} · 由你接話</p>}{pending&&!busy&&<div className="story-retry">這個回合尚待確認。<button onClick={()=>turn(null,true)}>以原回合重試</button><button onClick={()=>openWorld(world.id)}>重新載入核對</button></div>}{!ready&&<button className="story-offline" onClick={()=>openModal('settings')}>AI 尚未設定 · 連接模型後開始自由對話</button>}<textarea ref={input} aria-label="自由輸入對白或行動" placeholder={selected?`對${selected.name}說些什麼，或描述你的行動…`:'描述行動，或透過「山河」尋找可以見面的人…'} value={text} onFocus={()=>setVisibleThrough(null)} maxLength={2000} disabled={busy||!!pending} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();turn()}}}/><div className="story-quick-replies">{!unread&&selected&&<><button disabled={busy||!!pending||!ready} onClick={()=>turn(null,false,'繼續')}>先聽下去</button><button disabled={busy||!!pending||!ready} onClick={()=>turn(null,false,'剛才那件事，可以再說一些嗎？')}>追問剛才的事</button></>}{(world.incidentActions||[]).map(a=><button key={a.id} disabled={busy||!!pending} onClick={()=>turn({kind:'incident',operation:a.id})}>{a.label}</button>)}</div><div className="story-compose-footer"><small>Enter 接話 · Shift + Enter 換行</small><button title="讓當前人物接續行動，不代替你作決定" disabled={busy||!!pending||(!unread&&(!selected||!ready))} onClick={()=>unread?nextBeat():turn(null,false,'繼續')}>{unread?'下一段':'繼續'}</button><button className="story-send" aria-label="送出對白" disabled={busy||!!pending||!text.trim()||(!ready&&text.trim()!=='系統'&&!/^(系統|心想|內心|默想)[：: ]/.test(text))} onClick={()=>turn()}><Send size={18}/></button></div></div>
 <footer className="story-dialogue-foot"><span>✦ 第 {world.revision} 回合 · 已保存</span><span>重要決定，始終由你。</span></footer></section></>}
 {error&&<div className="story-error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="關閉提示"><X size={16}/></button></div>}{toast&&<div className="story-toast" role="status">{toast}</div>}
 {modal&&<div className="story-overlay" onClick={e=>{if(e.target===e.currentTarget)setModal(null)}}><section className={`story-modal ${modal==='map'?'story-map-modal':''}`} role="dialog" aria-modal="true" aria-labelledby="story-modal-title" ref={modalRef} tabIndex={-1}><header><div><small className="story-kicker">問道九州 · 山中卷宗</small><h2 id="story-modal-title">{({settings:'連線與設定',memory:'記憶檔案館',character:'洛河 · 自身',people:'相識之人',map:'太虛宗 · 山河',time:'光陰流轉',save:'世界線與存檔',promise:'言出，便留下痕跡',developer:'開發者 · 人物與生成依據'})[modal]}</h2></div><button aria-label="關閉面板" onClick={()=>setModal(null)}><X size={20}/></button></header><div className="story-modal-body">
 {modal==='settings'&&<><form method="post" action="/signout-with-chatgpt"><button type="submit" className="story-text-button">登出本次登入</button></form><p>帳號負責保存世界；模型負責理解與接話。未連接時仍可移動、修行、等待與查閱紀錄。</p><label>AI Provider<select value={provider} onChange={e=>{setProvider(e.target.value);setConnection(null);setModels([]);setKey('');setModel('')}}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option></select></label><label>本次工作階段 API Key<input type="password" autoComplete="off" value={key} maxLength={2048} onChange={e=>{setKey(e.target.value);setConnection(null)}} placeholder={list.configured[provider]?'已配置伺服器金鑰，可留空':'在此輸入金鑰，不要貼到對話裡'}/></label><small>金鑰僅留在本頁記憶體，經 HTTPS 傳給後端代理；不寫入世界、記憶或瀏覽器儲存。重新整理需重填。模型請求會由你的 API 帳戶計費。</small><label>模型 ID<input list="story-models" value={model} onChange={e=>setModel(e.target.value)} placeholder="測試連線後，選擇支援文字與 JSON 輸出的模型"/><datalist id="story-models">{models.map(m=><option key={m} value={m}/>)}</datalist></label><button className="story-primary" onClick={testAI} disabled={busy}>測試服務金鑰與讀取模型</button>{connection&&<p className="story-status">{connection.message}</p>}<div className="story-setting-row"><span>畫面顯示</span><button onClick={()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>setError('此裝置不支援全螢幕'));else document.exitFullscreen?.()}}><Maximize2 size={16}/> 切換全螢幕</button></div><details><summary>此版本的能力與邊界</summary><p>可自由交談、查詢自身、表達內心、移動、等待、修行、使用療傷丹、有限日常動作。攻擊、偷竊、交易、動態生成角色與新地圖尚未開放，不會假裝成功。NPC 以日程和事件結算；關係數值目前只由可驗證的承諾事件變動。敘事有格式及來源檢查，仍不能保證模型絕不出現語意矛盾。</p><p>尚未開放戰鬥、玩家境界突破、婚姻、生死與完整經濟。NPC 目前各有一階段的成長規則。六處地點各有獨立背景。每回合可有多段日常互動；重要表態仍由玩家決定。網站關閉期間不按現實時間推進。</p></details></>}
 {modal==='memory'&&<><form className="story-search" onSubmit={e=>{e.preventDefault();memory()}}><input aria-label="搜尋已知記憶" placeholder="搜尋你實際知道的事情…" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy}>查詢</button></form><div className="story-tabs">{[['all','全部'],['important','重要'],['promise','承諾'],['speech','對白'],['event','事件']].map(([k,n])=><button className={category===k?'active':''} onClick={()=>setCategory(k)} key={k}>{n}</button>)}<button onClick={()=>setModal('promise')}>＋ 許下承諾</button></div><small>顯示最近 200 筆符合條件的已知事件；對話原文可在主畫面向前翻閱。</small>{detail?<article className="story-memory-detail"><button onClick={()=>setDetail(null)}>← 返回卷宗</button><h3>{detail.content}</h3><p>{day(detail.time)} · {world.places[detail.location]?.name}</p><p>來源：{detail.source}</p><p>參與：{detail.actors?.map(a=>names[a]||a).join('、')}</p><p>{detail.type==='speech'?'這是曾說出的話，不代表話中主張已被證實。':'此事件已存入世界線帳本。'}</p><small>事件編號 {detail.id}</small></article>:<div className="story-memory-list">{filtered.length?filtered.map(e=><button key={e.id} onClick={()=>setDetail(e)}><span><BookOpen size={17}/>{e.content}</span><small>{day(e.time)} · {world.places[e.location]?.name} · {e.source}</small></button>):<p>尚無符合條件的記憶。</p>}</div>}</>}
 {modal==='character'&&<><div className="story-character-top"><Portrait id="player"/><div><h3>洛河</h3><p>棲風峰弟子 · {world.player.age} 歲<br/>{world.player.realm} · 純風靈根</p></div></div><div className="story-stat-grid"><div><small>健康</small><strong>{Math.round(world.player.health)} / 100</strong></div><div><small>靈石</small><strong>{world.player.money}</strong></div><div><small>修行累積</small><strong>{(world.player.trainingMinutes/60).toFixed(1)} 小時</strong></div><div><small>根基進度</small><strong>{world.player.progress.toFixed(1)}%</strong></div></div><p><small>根基達標不會自動突破；突破條件模組尚未開放。</small></p><h3>行囊與傷勢</h3>{Object.entries(world.player.items).map(([n,v])=><div className="story-setting-row" key={n}><span>{n} × {v}</span>{n==='療傷丹'&&<button disabled={busy||v<1||!!pending} onClick={()=>turn({kind:'consume',item:n})}>服用一枚</button>}</div>)}<p>{world.player.injuries.length?world.player.injuries.map(i=>`${i.name} · 尚需 ${Math.ceil(i.remaining/60)} 小時`).join('、'):'目前沒有記錄中的傷勢。'}</p></>}
 {modal==='people'&&<><p>只顯示相識和實際見過的人。離開視線後，保留的是最後一次相見，不是即時追蹤。</p>{world.contacts.map(n=><div className="story-person-card" key={n.id}><Portrait id={n.id}/><div><h3>{n.name}</h3><p>{n.role} · 上次已知修為：{n.realm}</p><small>{world.npcs.some(x=>x.id===n.id)?'此刻在場':`最後見於${world.places[n.lastLocation].name}，${day(n.lastSeen)}`}</small></div></div>)}<p className="story-small">信任與戒備等判斷保存在 NPC 狀態中；玩家透過言行體會，不直接讀取別人的內心數值。</p></>}
 {modal==='map'&&<><p>尋人輔助已開啟 · 顯示實際位置，但不會讓 NPC 獲得遠方情報。</p><div className="story-map"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{[['gate','square'],['square','library'],['square','court'],['court','home'],['home','room']].map(([a,b])=><line key={a+b} x1={world.places[a].x} y1={world.places[a].y} x2={world.places[b].x} y2={world.places[b].y}/>)}</svg>{Object.entries(world.places).map(([id,p])=><button key={id} className={mapPlace===id?'active':''} style={{left:p.x+'%',top:p.y+'%'}} onClick={()=>setMapPlace(id)}><span>◇</span>{p.name}<small>{world.player.location===id?'洛河在此':`步行 ${route(world.player.location,id).minutes} 分鐘`}</small><small className="map-names">{world.locator.filter(n=>!n.travel&&n.location===id).map(n=>n.name).join('、')||'目前無人在此'}</small></button>)}</div>{mapPlace&&<article className="map-destination"><img src={ART.scenes[mapPlace]} alt={world.places[mapPlace].name}/><div><h3>{world.places[mapPlace].name}</h3><p>{world.places[mapPlace].description}</p><p>在場：{[...(world.player.location===mapPlace?['洛河']:[]),...world.locator.filter(n=>!n.travel&&n.location===mapPlace).map(n=>n.name)].join('、')||'無'}</p><button className="story-primary" disabled={busy||!!pending||world.player.location===mapPlace} onClick={()=>turn({kind:'move',place:mapPlace})}>{world.player.location===mapPlace?'目前所在':`前往 · 步行 ${route(world.player.location,mapPlace).minutes} 分鐘`}</button></div></article>}<h3>路上的人</h3>{world.locator.filter(n=>n.travel).length?world.locator.filter(n=>n.travel).map(n=><p key={n.id}>{n.name} · 正前往{world.places[n.travel.to]?.name} · 約 {Math.max(0,Math.ceil(n.travel.arrive-world.time))} 分鐘後抵達</p>):<p>此刻沒有人在途中。</p>}<small>選擇地點查看，再確認前往。人物可能在你抵達前離開；約定期限可能中斷旅程。</small></>}
 {modal==='developer'&&list.isDeveloper&&<DeveloperPanel data={developerData} world={world} busy={busy||!!pending} onSelect={actor=>run(()=>loadDeveloper(actor))} onEdit={action=>turn({kind:'personality-edit',...action})}/>}
 {modal==='time'&&<><p>你可以安靜度日。別人的修行、職責、路程與事件，也會在這段光陰裡繼續。</p><div className="story-tabs">{[[60,'一小時'],[360,'六小時'],[1440,'一天'],[10080,'七天'],[43200,'一月'],[129600,'三月'],[518400,'一年']].map(([v,n])=><button key={v} className={minutes===v?'active':''} onClick={()=>setMinutes(v)}>{n}</button>)}</div><label>自訂時間（分鐘，最多五年）<input type="number" min={1} max={2592000} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label className="story-checkbox"><input type="checkbox" checked={training} onChange={e=>setTraining(e.target.checked)}/> 這段時間用於修行</label><p>約定期限會中斷快進。只會向你報告親歷或合理得知的變化。</p><button className="story-primary" disabled={busy||!!pending||minutes<1} onClick={()=>turn({kind:training?'train':'wait',minutes})}>{training?'開始修行':'讓光陰流轉'}</button></>}
 {modal==='promise'&&<><p>自由對話中的「我答應」先保留為台詞。重要約定在此由你明確登記，避免 AI 替你作出承諾。</p><label>向誰承諾<select value={target||''} onChange={e=>setTarget(e.target.value)}>{world.npcs.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>約定內容<select value={promiseKind} onChange={e=>setPromiseKind(e.target.value)}><option value="train">完成指定時間的修行</option><option value="visit">期限前到另一處與對方見面</option></select></label>{promiseKind==='visit'?<label>見面地點<select value={promisePlace} onChange={e=>setPromisePlace(e.target.value)}>{Object.entries(world.places).filter(([id])=>id!==world.player.location).map(([id,p])=><option key={id} value={id}>{p.name}</option>)}</select></label>:<label>需要累積修行（分鐘）<input type="number" min={1} max={43200} value={promiseTraining} onChange={e=>setPromiseTraining(Number(e.target.value))}/></label>}<label>幾小時內完成<input type="number" min={1} max={8640} value={promiseHours} onChange={e=>setPromiseHours(Number(e.target.value))}/></label><small>這是你單方面許下的承諾；不會強迫對方改變日程或保證對方在指定地點等候。</small><button className="story-primary" disabled={!selected||busy||!!pending} onClick={()=>turn({kind:'promise',to:target,promiseKind,place:promisePlace,requiredMinutes:promiseTraining,afterMinutes:promiseHours*60})}>由我確認，許下承諾</button><h3>已留下的約定</h3>{world.promises.map(p=><article className="story-promise" key={p.id}><p>{p.description}</p><small>{day(p.due)} 截止 · {({active:'尚待履行',fulfilled:'已履行',missed:'已逾期'})[p.status]}</small>{p.kind==='train'&&p.status==='fulfilled'&&!p.knownByRecipient&&<button disabled={busy||!!pending||!world.npcs.some(n=>n.id===p.to)} onClick={()=>turn({kind:'report-promise',promise:p.id})}>向{names[p.to]}當面回報</button>}</article>)}</>}
 {modal==='save'&&<><p>每個正式回合自動保存。手動存檔保留可重返的歷史節點；讀取時會建立新分支，保留原來的因果。</p><div className="story-tabs"><button className="story-primary" onClick={save} disabled={busy||!!pending}>保存此刻</button><button onClick={()=>branch()} disabled={busy||!!pending}>從此刻建立分支</button></div>{list.saves.filter(s=>s.world===world.id).map(s=><div className="story-setting-row" key={s.id}><span>{s.name}<small>{new Date(s.created).toLocaleString('zh-TW')}</small></span><button disabled={busy||!!pending} onClick={()=>branch(s.id)}>從這裡重新生活</button></div>)}<h3>其他世界線</h3>{list.worlds.map(w=><div className="story-setting-row" key={w.id}><span>{w.name}<small>{w.revision} 回合</small></span><button disabled={busy||w.id===world.id} onClick={()=>openWorld(w.id)}>{w.id===world.id?'目前世界':'進入'}</button></div>)}</>}
 </div></section></div>}
 </main>;
}
