'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OBSTACLES,validPoint,distance} from '../../lib/game/spatial.mjs';
type Props={state:any,busy:boolean,onAction:(a:any)=>void,onTalk:(id:string)=>void};
export default function World3D({state,busy,onAction,onTalk}:Props){const host=useRef<HTMLDivElement>(null),current=useRef({state,busy,onAction,onTalk}),[error,setError]=useState('');current.current={state,busy,onAction,onTalk};const [near,setNear]=useState<any>(null),[live,setLive]=useState(false);
useEffect(()=>{if(!live)return;const id=setInterval(()=>{if(!current.current.busy)current.current.onAction({type:'wait',minutes:1})},20000);return()=>clearInterval(id)},[live]);
useEffect(()=>{if(!host.current)return;const el=host.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{setError('這個裝置未能啟用 WebGL。請使用支援 3D 的瀏覽器；地圖與文字操作仍可使用。');return;}renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color('#a6c7be');scene.fog=new THREE.Fog('#a6c7be',55,180);const camera=new THREE.PerspectiveCamera(48,1,.1,250);scene.add(new THREE.HemisphereLight('#f3ffe5','#416354',2.5));const sun=new THREE.DirectionalLight('#fff2cc',3);sun.position.set(-25,50,30);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-50,right:50,top:50,bottom:-50});scene.add(sun);
const mats:THREE.Material[]=[];const geometries:THREE.BufferGeometry[]=[];function mat(color:string){const m=new THREE.MeshStandardMaterial({color,roughness:.9});mats.push(m);return m}const terrainSeed=current.current.state.places?.[current.current.state.player.location]?.terrainSeed||0;const grass=mat(terrainSeed?'#5e8062':'#688b6c'),stone=mat('#c1c8ab'),wood=mat('#644b38'),wall=mat('#e0dbc1'),roof=mat(terrainSeed?'#715d3f':'#365c55'),trunk=mat('#655842'),leaf=mat('#39775a');function mesh(g:THREE.BufferGeometry,m:THREE.Material,x=0,y=0,z=0,parent:THREE.Object3D=scene){geometries.push(g);const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}const ground=mesh(new THREE.PlaneGeometry(80,80),grass);ground.rotation.x=-Math.PI/2;mesh(new THREE.BoxGeometry(8,.13,70),stone,0,.08,0);mesh(new THREE.BoxGeometry(55,.13,6),stone,0,.1,3);
for(const o of OBSTACLES){mesh(new THREE.BoxGeometry(o.w,5,o.d),wall,o.x,2.5,o.z);const r=mesh(new THREE.ConeGeometry(o.w*.72,4,4),roof,o.x,6,o.z);r.rotation.y=Math.PI/4;for(const dx of [-o.w/2+.4,o.w/2-.4])mesh(new THREE.CylinderGeometry(.35,.35,5,8),wood,o.x+dx,2.5,o.z+o.d/2+.4);mesh(new THREE.BoxGeometry(2.2,3,.15),wood,o.x,1.5,o.z+o.d/2+.1);}
for(let i=0;i<26;i++){const angle=i/26*Math.PI*2+(terrainSeed%11)*.03,r=28+((i+terrainSeed)%3)*3,x=Math.sin(angle)*r,z=Math.cos(angle)*r;if(Math.abs(x)<7)continue;mesh(new THREE.CylinderGeometry(.3,.5,6,6),trunk,x,3,z);mesh(new THREE.ConeGeometry(2.8,8,7),leaf,x,8,z);mesh(new THREE.ConeGeometry(3.4,6,7),leaf,x,5.5,z);}
for(let i=0;i<12;i++){const a=i/12*Math.PI*2;mesh(new THREE.ConeGeometry(24,45+(i%3)*12,5),mat(i%2?'#72998b':'#82a99b'),Math.sin(a)*100,10,Math.cos(a)*100)}
function label(text:string){const canvas=document.createElement('canvas');canvas.width=384;canvas.height=80;const ctx=canvas.getContext('2d')!;ctx.fillStyle='rgba(17,37,29,.85)';ctx.fillRect(0,0,384,80);ctx.fillStyle='#f3ecd1';ctx.font='32px sans-serif';ctx.textAlign='center';ctx.fillText(text,192,52);const material=new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false});mats.push(material);const sprite=new THREE.Sprite(material);sprite.scale.set(6,1.25,1);sprite.position.y=5.4;return sprite}
function person(color:string,name:string){const group=new THREE.Group(),robe=mat(color),skin=mat('#e9c5a2'),hair=mat('#20322d');mesh(new THREE.CylinderGeometry(.5,.85,2,8),robe,0,1.75,0,group);mesh(new THREE.SphereGeometry(.53,12,8),skin,0,3.15,0,group);mesh(new THREE.SphereGeometry(.54,12,8),hair,0,3.42,-.08,group);const left=new THREE.Group(),right=new THREE.Group();left.position.set(-.63,2.3,0);right.position.set(.63,2.3,0);group.add(left,right);mesh(new THREE.CylinderGeometry(.17,.23,1.4,6),robe,0,-.55,0,left);mesh(new THREE.CylinderGeometry(.17,.23,1.4,6),robe,0,-.55,0,right);const legs=[mesh(new THREE.BoxGeometry(.28,.9,.35),wood,-.25,.45,0,group),mesh(new THREE.BoxGeometry(.28,.9,.35),wood,.25,.45,0,group)];group.add(label(name));scene.add(group);return {group,left,right,legs};}
const hero=person('#d7dab6','洛河'),people=new Map<string,ReturnType<typeof person>>();let lastLocation='',raf=0,last=performance.now(),elapsed=0;const colors:any={shen:'#e8ebdf',yan:'#829f98',jiang:'#658fa8',gu:'#93918a'};
const observer=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});observer.observe(el);const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function click(e:PointerEvent){if(current.current.busy)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObject(ground);if(hits.length){const p=current.current.state.player.position||{x:0,z:10},target={x:hits[0].point.x,z:hits[0].point.z},d=distance(p,target),k=Math.min(1,10/Math.max(d,.01));const dest={x:p.x+(target.x-p.x)*k,z:p.z+(target.z-p.z)*k};if(validPoint(dest))current.current.onAction({type:'walk',position:dest});}}
function key(e:KeyboardEvent){if((e.target as HTMLElement).closest('input,textarea,select')||current.current.busy)return;const dirs:any={w:[0,-1],ArrowUp:[0,-1],s:[0,1],ArrowDown:[0,1],a:[-1,0],ArrowLeft:[-1,0],d:[1,0],ArrowRight:[1,0]};const d=dirs[e.key];if(d){e.preventDefault();const p=current.current.state.player.position||{x:0,z:10},dest={x:p.x+d[0]*4,z:p.z+d[1]*4};if(validPoint(dest))current.current.onAction({type:'walk',position:dest});}}
renderer.domElement.addEventListener('pointerup',click);window.addEventListener('keydown',key);let nearId='';function frame(){raf=requestAnimationFrame(frame);const now=performance.now(),dt=Math.min((now-last)/1000,.1);last=now;elapsed+=dt;const s=current.current.state,p=s.player.position||{x:0,z:10};if(s.player.location!==lastLocation){hero.group.position.set(p.x,0,p.z);lastLocation=s.player.location;}const target=new THREE.Vector3(p.x,0,p.z),delta=target.clone().sub(hero.group.position),walking=delta.length()>.1;if(walking){hero.group.rotation.y=Math.atan2(delta.x,delta.z);hero.group.position.lerp(target,Math.min(1,dt*3));}const phase=elapsed*8;hero.left.rotation.x=walking?Math.sin(phase)*.5:Math.sin(elapsed)*.03;hero.right.rotation.x=-hero.left.rotation.x;hero.legs[0].rotation.x=walking?Math.sin(phase)*.4:0;hero.legs[1].rotation.x=-hero.legs[0].rotation.x;
const ids=new Set(s.npcs.map((n:any)=>n.id));for(const [id,n] of people)if(!ids.has(id)){scene.remove(n.group);people.delete(id)}let closest:any=null,best=12;for(const n of s.npcs){let figure=people.get(n.id);if(!figure){figure=person(colors[n.id]||'#c1a779',n.name);figure.group.position.set(n.position.x,0,n.position.z);people.set(n.id,figure);}const desired=new THREE.Vector3(n.position.x,0,n.position.z),diff=desired.clone().sub(figure.group.position),moving=diff.length()>.08;if(moving)figure.group.rotation.y=Math.atan2(diff.x,diff.z);figure.group.position.lerp(desired,Math.min(1,dt*2));figure.left.rotation.x=moving?Math.sin(phase+n.id.length)*.4:Math.sin(elapsed+n.id.length)*.06;figure.right.rotation.x=-figure.left.rotation.x;figure.legs[0].rotation.x=moving?Math.sin(phase)*.3:0;figure.legs[1].rotation.x=-figure.legs[0].rotation.x;const dist=distance(p,n.position);if(dist<best){best=dist;closest=n;}}
if((closest?.id||'')!==nearId){nearId=closest?.id||'';setNear(closest)}camera.position.lerp(new THREE.Vector3(hero.group.position.x,30,hero.group.position.z+34),Math.min(1,dt*4));camera.lookAt(hero.group.position.x,0,hero.group.position.z-3);renderer.render(scene,camera);}
camera.position.set(0,30,44);frame();return()=>{cancelAnimationFrame(raf);observer.disconnect();renderer.domElement.removeEventListener('pointerup',click);window.removeEventListener('keydown',key);scene.traverse(o=>{if(o instanceof THREE.Sprite)(o.material as THREE.SpriteMaterial).map?.dispose()});geometries.forEach(g=>g.dispose());mats.forEach(m=>{if(m instanceof THREE.SpriteMaterial)m.map?.dispose();m.dispose()});renderer.dispose();renderer.domElement.remove();};},[]);
function move(dx:number,dz:number){const p=state.player.position||{x:0,z:10};onAction({type:'walk',position:{x:p.x+dx*4,z:p.z+dz*4}})}
return <div className="world3d"><div ref={host} className="three-canvas"/>{error&&<div className="three-error">{error}</div>}<div className="three-top"><span>{state.places?.[state.player.location]?.name||'棲風峰'}</span><span>3D 程式模型 · 暫用美術</span></div><div className="three-bottom"><span>WASD / 方向鍵 / 點擊地面行走<br/><small>每次行走提交座標與時間。</small></span>{near?<button disabled={busy} onClick={()=>onTalk(near.id)}>與 {near.name} 交談</button>:<span>走近人物即可交談</span>}</div><div className="dpad"><button aria-label="向前走" disabled={busy} onClick={()=>move(0,-1)}>↑</button><div><button aria-label="向左走" disabled={busy} onClick={()=>move(-1,0)}>←</button><button aria-label="向後走" disabled={busy} onClick={()=>move(0,1)}>↓</button><button aria-label="向右走" disabled={busy} onClick={()=>move(1,0)}>→</button></div></div><label className="world-live"><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/> 世界自行運轉 <small>開啟時每 20 秒推進 1 分鐘</small></label></div>}
