import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';
export const worlds=sqliteTable('worlds',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),revision:integer('revision').notNull().default(0),state:text('state').notNull(),created:text('created').notNull()});
export const saves=sqliteTable('saves',{id:text('id').primaryKey(),owner:text('owner').notNull(),world:text('world').notNull(),name:text('name').notNull(),state:text('state').notNull(),created:text('created').notNull()});

import {primaryKey,foreignKey,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const eventLedger=sqliteTable('event_ledger',{world:text('world').notNull().references(()=>worlds.id),id:text('id').notNull(),minute:integer('minute').notNull(),type:text('type').notNull(),location:text('location').notNull(),content:text('content').notNull(),source:text('source').notNull(),data:text('data').notNull()},t=>[primaryKey({columns:[t.world,t.id]})]);
export const knowledge=sqliteTable('actor_knowledge',{world:text('world').notNull(),actor:text('actor').notNull(),event:text('event').notNull(),acquired:integer('acquired').notNull(),status:text('status').notNull().default('witnessed')},t=>[primaryKey({columns:[t.world,t.actor,t.event]}),foreignKey({columns:[t.world,t.event],foreignColumns:[eventLedger.world,eventLedger.id]})]);
export const turnCommits=sqliteTable('turn_commits',{world:text('world').notNull().references(()=>worlds.id),request:text('request').notNull(),revision:integer('revision').notNull(),result:text('result').notNull()},t=>[primaryKey({columns:[t.world,t.request]}),uniqueIndex('turn_revision_unique').on(t.world,t.revision)]);
export const sealedTruths=sqliteTable('sealed_truths',{world:text('world').notNull().references(()=>worlds.id),id:text('id').notNull(),hash:text('hash').notNull(),data:text('data').notNull()},t=>[primaryKey({columns:[t.world,t.id]})]);

export const storyMessages=sqliteTable('story_messages',{world:text('world').notNull().references(()=>worlds.id),id:text('id').notNull(),seq:integer('seq').notNull(),minute:integer('minute').notNull(),location:text('location').notNull(),speaker:text('speaker').notNull(),kind:text('kind').notNull(),content:text('content').notNull(),audience:text('audience').notNull(),event:text('event'),performance:text('performance').notNull().default('{}')},t=>[primaryKey({columns:[t.world,t.id]}),uniqueIndex('story_message_sequence').on(t.world,t.seq)]);
export const storyRequests=sqliteTable('story_requests',{world:text('world').notNull().references(()=>worlds.id),request:text('request').notNull(),fingerprint:text('fingerprint').notNull(),status:text('status').notNull(),lease:text('lease').notNull(),expires:integer('expires').notNull(),created:integer('created').notNull(),prepared:text('prepared')},t=>[primaryKey({columns:[t.world,t.request]})]);
