import {validPoint,distance,npcPosition,generateArea} from './spatial.mjs';
export const VERSION=2;
import WORLD from '../../data/taixu.json' with {type:'json'};
export const NPCS=WORLD.npcs;
export const PLACES=WORLD.places;
export const EDGES=WORLD.edges;
export function places(s){return {...PLACES,...(s?.generatedPlaces||{})};}
export function definitions(s){return {...NPCS,...(s?.generatedNPCs||{})};}
export function route(a,b,s){const q=[[a,0,[]]],seen=new Set();while(q.length){q.sort((x,y)=>x[1]-y[1]);const [p,t,path]=q.shift();if(p===b)return {minutes:t,path};if(seen.has(p))continue;seen.add(p);for(const [x,y,d] of [...EDGES,...(s?.generatedEdges||[])]){if(x===p||y===p)q.push([x===p?y:x,t+d,[...path,x===p?y:x]]);}}throw Error('沒有可通行路線');}
const clone=x=>JSON.parse(JSON.stringify(x));
export function initial(id){return {version:VERSION,id,revision:0,time:480,player:{name:'洛河',age:15,realm:'聚氣初期',progress:0,health:100,injuries:[],money:10,items:{木劍:1,療傷丹:1},location:'gate',position:{x:0,z:10}},generatedPlaces:{},generatedNPCs:{},generatedEdges:[],npcs:Object.fromEntries(Object.keys(NPCS).map(n=>[n,{location:['shen','yan'].includes(n)?'gate':'home',travel:null,progress:0,relations:{trust:20,respect:10,closeness:0,caution:10},beliefs:[]}])),events:[],receipts:{},promises:[],queue:[{id:'assembly',at:7*1440+480,type:'assembly',interrupt:true}],truth:{id:'missing-books',sealedAt:0,cause:'庫房登記錯誤，舊卷已被送往主峰修繕',culprit:null,evidence:['修繕收據','庫房出入簿'],naturalOutcome:'三十日後修繕歸還'},known:['gate','square','home','court','room','library'],enrolled:false,seed:1731};}
export function laboratory(id){const s=initial(id);s.experiment='qifeng-animation-v1';s.enrolled=true;s.player.location='home';s.npcs.shen.location='home';for(const id of ['yan','jiang','gu'])s.npcs[id].location='court';emit(s,'experiment','洛河與沈滄月在棲風峰庭院開始移動、交談與記憶實驗。',['player','shen'],'home','實驗場登記');return s;}
export function positionOf(s,id){if(s.experiment&&id==='shen'&&s.npcs[id].location==='home')return {x:-6,z:2};return npcPosition(id,s.time);}
function emit(s,type,content,actors=['player'],location=s.player.location,source='親身經歷',changes={}){const id=`${s.id}:${s.events.length+1}`;const e={id,timeline:s.id,time:s.time,recordedAt:new Date().toISOString(),type,content,actors,location,source,confirmed:true,knowers:[...new Set(actors)],changes,links:[]};s.events.push(e);return e;}
export function retrieve(s,actor,query=''){return s.events.filter(e=>e.knowers.includes(actor)).map(e=>({...e,score:(e.actors.includes(actor)?3:0)+(['promise','enroll','experiment'].includes(e.type)?20:0)+([...query].some(c=>e.content.includes(c))?2:0)})).sort((a,b)=>b.score-a.score||b.time-a.time).slice(0,30);}
function witnesses(s){return ['player',...Object.keys(s.npcs).filter(n=>!s.npcs[n].travel&&s.npcs[n].location===s.player.location&&distance(s.player.position||{x:0,z:10},positionOf(s,n))<=12)];}
export function parse(text,s){text=text.trim();if(!text||text.length>2000)throw Error('請輸入 1–2000 字的行動');for(const [id,p] of Object.entries(places(s)))if(text.includes(p.name)&&/去|前往|走|回/.test(text))return {type:'move',target:id};if(/修煉|閉關|練功/.test(text)){let m=text.match(/(\d+)\s*(小時|天|日|個月|月|年)/);return {type:'train',minutes:m?Number(m[1])*({小時:60,天:1440,日:1440,個月:43200,月:43200,年:518400}[m[2]]):60};}if(/服用|吃下|使用/.test(text)&&/療傷丹/.test(text))return {type:'consume',item:'療傷丹'};if(/入門|拜師|測試/.test(text))return {type:'enroll'};if(/繼續|等待/.test(text))return {type:'wait',minutes:60};return {type:'speech',text};}
export function advance(s,minutes,training=false){if(!Number.isInteger(minutes)||minutes<1||minutes>5*518400)throw Error('時間須為 1 分鐘至 5 年');const end=s.time+minutes,start=s.time;let stopped=false;while(s.time<end){let day=Math.floor(s.time/1440);const schedule=[day*1440+360,day*1440+1080,(day+1)*1440+360].filter(t=>t>s.time);let next=Math.min(end,...schedule,...s.queue.filter(q=>q.at>s.time).map(q=>q.at),...Object.values(s.npcs).filter(n=>n.travel).map(n=>n.travel.arrive));const dt=next-s.time;s.player.injuries=s.player.injuries.map(i=>({...i,remaining:Math.max(0,i.remaining-dt)})).filter(i=>i.remaining>0);s.player.health=Math.min(100,s.player.health+dt/1440*5);if(training&&s.enrolled)s.player.progress=Math.min(100,s.player.progress+dt/1440*0.12);for(const n of Object.values(s.npcs))n.progress=Math.min(100,n.progress+dt/43200*0.25);const oldMonth=Math.floor(s.time/43200);s.time=next;const months=Math.floor(s.time/43200)-oldMonth;if(months&&s.enrolled){s.player.money+=months*3;emit(s,'income',`收到 ${months*3} 枚下品靈石月例。`,['player'],s.player.location,'宗門月例',{money:months*3});}for(const [id,n] of Object.entries(s.npcs)){if(n.travel&&n.travel.arrive<=s.time){n.location=n.travel.to;n.travel=null;}if((s.time%1440===360||s.time%1440===1080)&&!(s.experiment&&id==='shen')){const target=s.time%1440===360?(n.homeLocation|| (id==='shen'?'home':'court')):'home';if(n.location!==target&&!n.travel)n.travel={to:target,arrive:s.time+route(n.location,target,s).minutes};}}
const due=s.queue.filter(q=>q.at<=s.time);s.queue=s.queue.filter(q=>q.at>s.time);for(const q of due){if(q.type==='assembly'){emit(s,'notice','宗門召集新弟子。使者送來通知，請你決定是否前往主峰廣場。',['player'],s.player.location,'使者送信');if(q.interrupt){stopped=true;break;}}else if(q.type==='message')emit(s,'notice',q.content,q.knowers??['player'],q.location??s.player.location,'通報');}if(stopped)break;}
emit(s,'time',`${training?'修煉':'等待'} ${s.time-start} 分鐘${stopped?'；重要通知中斷了快進':''}。`,['player'],s.player.location,'親身經歷',{elapsed:s.time-start});return stopped;}
export function turn(previous,request){if(previous.receipts[request.id])return clone(previous);if(!request.id||typeof request.id!=='string'||request.id.length>100)throw Error('缺少有效回合 ID');if(request.revision!==previous.revision)throw Error('存檔版本已改變，請重新載入');const s=clone(previous),a=request.action;s.version=VERSION;s.player.position??={x:0,z:10};s.generatedPlaces??={};s.generatedNPCs??={};s.generatedEdges??=[];if(!a||!['move','train','consume','enroll','wait','speech','walk','explore'].includes(a.type))throw Error('尚不支援此行動');let reply='';if(a.type==='move'){if(!places(s)[a.target]||!s.known.includes(a.target))throw Error('尚未知曉該地點');const from=s.player.location,r=route(from,a.target,s);if(r.minutes){const interrupted=advance(s,r.minutes);if(interrupted){reply='收到重要通知，旅程尚未開始完成。';}else{s.player.location=a.target;s.player.position={x:0,z:10};emit(s,'move',`從${places(s)[from].name}前往${places(s)[a.target].name}，耗時 ${r.minutes} 分鐘。`,witnesses(s),a.target,'親身經歷',{location:a.target});reply=places(s)[a.target].description;}}else reply='你已經在這裡。';}
if(a.type==='walk'){if(!validPoint(a.position))throw Error('此處不可通行');const d=distance(s.player.position,a.position);if(d>15)throw Error('每次移動不得超過 15 公尺');if(d>0.1){const origin={...s.player.position};for(let i=1;i<=20;i++)if(!validPoint({x:origin.x+(a.position.x-origin.x)*i/20,z:origin.z+(a.position.z-origin.z)*i/20}))throw Error('路線被建築阻擋');advance(s,Math.max(1,Math.ceil(d/8)));s.player.position={x:a.position.x,z:a.position.z};emit(s,'walk',`在${places(s)[s.player.location].name}行走 ${d.toFixed(1)} 公尺。`,['player'],s.player.location,'親身經歷',{position:s.player.position});}reply='你循著山風移步。';}
if(a.type==='explore'){if(s.player.location!=='home')throw Error('請從棲風峰庭院探索東側山路');if(!s.generatedPlaces.grove){const generated=generateArea(s.id);s.generatedPlaces.grove=generated.place;s.generatedNPCs.newcomer=generated.npc;s.generatedEdges.push(['home','grove',12]);s.known.push('grove');s.npcs.newcomer={location:'grove',travel:null,homeLocation:'grove',progress:0,relations:{trust:10,respect:10,closeness:0,caution:20},beliefs:[]};emit(s,'discovery',`你沿宗門路標得知${generated.place.name}的位置。`,['player'],'home','宗門路標');}reply=`東側山路通往${s.generatedPlaces.grove.name}。地圖與新人物已固定保存，前往當地才能相遇。［規則生成，尚未接入 AI］`;}
if(a.type==='enroll'){if(s.player.location!=='gate')throw Error('請先到山門參加入門測試');if(s.enrolled)reply='你已是棲風峰弟子。';else{s.enrolled=true;emit(s,'enroll','洛河通過靈根測試，以純風靈根拜入棲風峰。',['player','shen','yan'],'gate','入門登記',{enrolled:true});s.npcs.shen.beliefs.push('洛河是自己的新弟子');for(const id of ['shen','yan']){const n=s.npcs[id];if(n.location!=='home'&&!n.travel)n.travel={to:'home',arrive:s.time+route(n.location,'home',s).minutes};}reply='測靈盤浮起清亮風光。入門登記完成，測試結果已送往棲風峰。你可以前往庭院熟悉環境。';}}
if(a.type==='train'){if(!s.enrolled)throw Error('先在山門完成入門測試');if(!['room','home','court'].includes(s.player.location))throw Error('請到居所、庭院或演武場修煉');advance(s,a.minutes,true);reply=`吐納結束，根基進度 ${s.player.progress.toFixed(1)}%。突破尚需功法與條件，原型不會自動升境。`;}
if(a.type==='wait'){advance(s,a.minutes);reply='風聲與日影漸漸移轉。世界時間已完成結算。';}
if(a.type==='consume'){if(a.item!=='療傷丹'||!s.player.items[a.item])throw Error('背包沒有此物品');s.player.items[a.item]--;s.player.health=Math.min(100,s.player.health+20);s.player.injuries=s.player.injuries.map(i=>({...i,remaining:Math.max(0,i.remaining-1440)})).filter(i=>i.remaining>0);emit(s,'consume','服用一枚療傷丹。',witnesses(s),s.player.location,'親身經歷',{item:'療傷丹',quantity:-1});reply='丹藥化開，藥力溫和地流過經脈。';}
if(a.type==='speech'){if(typeof a.text!=='string'||!a.text.trim()||a.text.length>2000)throw Error('無效文字');const present=witnesses(s).filter(n=>n!=='player');if(a.target&&!present.includes(a.target))throw Error('請靠近對方再交談');let target=(a.target&&present.includes(a.target)?a.target:null)??present.find(n=>a.text.includes(definitions(s)[n].name))??present[0];emit(s,'speech',`洛河：「${a.text}」`,['player',...present]);if(target){if(s.generatedNPCs[target]&&!s.npcs[target].metPlayer){s.npcs[target].metPlayer=true;emit(s,'meet',`${definitions(s)[target].name}向洛河介紹自己：${definitions(s)[target].background}`,['player',target]);}const memory=retrieve(s,target,a.text);if(/記得|記不記得/.test(a.text)){const important=memory.find(e=>e.type!=='speech'&&e.type!=='time');reply=`${definitions(s)[target].name}：${important?`我記得，${important.content}`:'這件事我並未親眼見過，也沒有人告訴我。'}`;}else reply=`${definitions(s)[target].name}：${definitions(s)[target].voice}\n［規則式回應：生成式 AI 尚未接入。你說的話已保存為在場者的共同記憶。］`;}else reply='你說的話落在山風裡。附近沒有可交談的人；系統已保存你的行動，但尚未接入 AI 以判定其他自由行動。';}
s.revision++;s.receipts[request.id]={revision:s.revision,reply};return s;}
export function visible(s){return {experiment:s.experiment,version:s.version,id:s.id,revision:s.revision,time:s.time,player:s.player,places:places(s),edges:[...EDGES,...(s.generatedEdges||[])],enrolled:s.enrolled,known:s.known,events:s.events.filter(e=>e.knowers.includes('player')).map(({knowers,...e})=>e),npcs:Object.entries(s.npcs).filter(([,n])=>n.location===s.player.location&&!n.travel).map(([id,n])=>({id,...definitions(s)[id],position:positionOf(s,id),relations:n.relations})),last:Object.values(s.receipts).at(-1)?.reply??(s.experiment?'棲風峰庭院實驗場已建立。點擊石路行走，走近沈滄月交談，或查看資料與記憶說明。':'山門收徒大典將啟。洛河站在青石階前，一陣風捲起衣角。')};}
export function branch(s,id){const b=clone(s);b.id=id;b.revision=0;b.receipts={};b.events=b.events.map(e=>({...e,id:e.id.replace(s.id,id),timeline:id,origin:e.id}));return b;}
