import {validPoint,distance} from './spatial.mjs';
export function clearSegment(a,b){const steps=Math.max(1,Math.ceil(distance(a,b)*4));for(let i=0;i<=steps;i++)if(!validPoint({x:a.x+(b.x-a.x)*i/steps,z:a.z+(b.z-a.z)*i/steps}))return false;return true;}
export function findPath(start,goal){if(!validPoint(start)||!validPoint(goal))return [];if(clearSegment(start,goal))return split(start,[goal]);const nodes=[];for(let x=-32;x<=32;x+=2)for(let z=-32;z<=32;z+=2)if(validPoint({x,z}))nodes.push({x,z});const near=p=>nodes.filter(n=>distance(p,n)<=4&&clearSegment(p,n)).sort((a,b)=>distance(p,a)-distance(p,b));const starts=near(start),ends=new Set(near(goal).map(n=>`${n.x},${n.z}`));const open=starts.map(n=>({p:n,g:distance(start,n),path:[n]})),seen=new Set();while(open.length){open.sort((a,b)=>a.g+distance(a.p,goal)-b.g-distance(b.p,goal));const cur=open.shift(),key=`${cur.p.x},${cur.p.z}`;if(seen.has(key))continue;seen.add(key);if(ends.has(key))return split(start,[...cur.path,goal]);for(const dx of [-2,0,2])for(const dz of [-2,0,2]){if(!dx&&!dz)continue;const n={x:cur.p.x+dx,z:cur.p.z+dz};if(Math.abs(n.x)>32||Math.abs(n.z)>32||seen.has(`${n.x},${n.z}`)||!clearSegment(cur.p,n))continue;open.push({p:n,g:cur.g+Math.hypot(dx,dz),path:[...cur.path,n]});}}return [];}
function split(start,points){const out=[];let previous=start;for(const end of points){const d=distance(previous,end),steps=Math.max(1,Math.ceil(d/7));for(let i=1;i<=steps;i++)out.push({x:previous.x+(end.x-previous.x)*i/steps,z:previous.z+(end.z-previous.z)*i/steps});previous=end;}return out;}
export function advancePose(current,target,dt,speed=12){const d=distance(current,target),k=d?Math.min(1,speed*Math.max(0,dt)/d):1;return {...current,x:current.x+(target.x-current.x)*k,z:current.z+(target.z-current.z)*k,walk:d>.05};}
export function facing(dx,dz,previous=0){if(Math.hypot(dx,dz)<.001)return previous;const sx=dx-dz,sy=(dx+dz)*.5;return Math.abs(sx)>Math.abs(sy)?(sx<0?1:2):(sy<0?3:0);}
export function animationCell(profile,direction,walk,seconds){return {column:walk?Math.floor(seconds*profile.walkFps)%profile.columns:0,row:profile.rowOffset+(profile.directionRows?.[direction]??direction)};}
// Preserve held keys across network writes; only keyup/blur/pause release them.
export function heldStep(keys,length=7){const up=keys.has('w')||keys.has('ArrowUp'),down=keys.has('s')||keys.has('ArrowDown'),left=keys.has('a')||keys.has('ArrowLeft'),right=keys.has('d')||keys.has('ArrowRight');let x=Number(down)-Number(up)+Number(right)-Number(left),z=Number(down)-Number(up)+Number(left)-Number(right);const d=Math.hypot(x,z);return d?{x:x/d*length,z:z/d*length}:null;}
export class MotionPresentation{
 constructor(position){this.pose={...position,walk:false,direction:0,phase:0};this.target={...position};this.pending=false;}
 propose(target){this.target={...target};this.pending=true;}
 confirm(position){this.target={...position};this.pending=false;}
 reject(position){this.target={...position};this.pending=false;}
 tick(dt){const before=this.pose,next=advancePose(before,this.target,dt,12),travel=distance(before,next);this.pose={...next,direction:facing(next.x-before.x,next.z-before.z,before.direction),phase:before.phase+travel*1.4};return this.pose;}
}
