// @ts-nocheck
import {getDb} from '../../../db';
import {ledgerWrites,newEventsWrites} from '../../../lib/game/persistence';
import {worlds,saves,eventLedger,knowledge,turnCommits} from '../../../db/schema';
import {eq,and} from 'drizzle-orm';
import {getChatGPTUser} from '../../chatgpt-auth';
import {initial,laboratory,turn,visible,parse,branch} from '../../../lib/game/engine.mjs';
export const dynamic="force-dynamic";
export async function GET(request:Request){return handle(request);}
export async function POST(request:Request){return handle(request);}
async function handle(request:Request){try{if(request.method==='POST'&&request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'拒絕跨來源提交'},{status:403});const user=await getChatGPTUser();if(!user)return Response.json({error:'請先以 ChatGPT 登入',signin:'/signin-with-chatgpt?return_to=%2F'},{status:401});const owner=user.userId,db=getDb();const b=request.method==='POST'?await request.json():{op:'list'};if(b.op==='list'){const w=await db.select({id:worlds.id,name:worlds.name,revision:worlds.revision}).from(worlds).where(eq(worlds.owner,owner));const sv=await db.select({id:saves.id,world:saves.world,name:saves.name,created:saves.created}).from(saves).where(eq(saves.owner,owner));return Response.json({worlds:w,saves:sv});}if(b.op==='new'){const id=crypto.randomUUID(),s=b.mode==='lab'?laboratory(id):initial(id);await db.insert(worlds).values({id,owner,name:String(b.name||'新的入門世界線').slice(0,60),state:JSON.stringify(s),created:new Date().toISOString()});return Response.json(visible(s));}if(b.op==='restore'||b.op==='branch'){let source;if(b.op==='restore'){const [sv]=await db.select().from(saves).where(and(eq(saves.id,b.save),eq(saves.owner,owner)));if(!sv)throw Error('存檔不存在');source=JSON.parse(sv.state);}else{const [w]=await db.select().from(worlds).where(and(eq(worlds.id,b.world),eq(worlds.owner,owner)));if(!w)throw Error('世界線不存在');source=JSON.parse(w.state);}if(source.mode==='story-v1')throw Error('對話世界線請使用新版介面');const id=crypto.randomUUID(),s=branch(source,id);await db.insert(worlds).values({id,owner,name:String(b.name||'歷史分支').slice(0,60),state:JSON.stringify(s),created:new Date().toISOString()});return Response.json(visible(s));}
const [w]=await db.select().from(worlds).where(and(eq(worlds.id,b.world),eq(worlds.owner,owner)));if(!w)throw Error('世界線不存在');const s=JSON.parse(w.state);if(s.mode==='story-v1')throw Error('對話世界線請使用新版介面');if(b.op==='load'||b.op==='memory'){const writes=await ledgerWrites(db,s);for(let i=0;i<writes.length;i+=40)await db.batch(writes.slice(i,i+40));if(b.op==='memory'){const rows=await db.select({data:eventLedger.data}).from(eventLedger).innerJoin(knowledge,and(eq(eventLedger.world,knowledge.world),eq(eventLedger.id,knowledge.event))).where(and(eq(eventLedger.world,w.id),eq(knowledge.actor,'player')));return Response.json({events:rows.map(r=>{const {knowers,...e}=JSON.parse(r.data);return e}).sort((a,b)=>a.time-b.time)});}return Response.json(visible(s));}if(b.op==='save'){const id=crypto.randomUUID();await db.insert(saves).values({id,owner,world:w.id,name:String(b.name||`第 ${Math.floor(s.time/1440)+1} 日存檔`).slice(0,60),state:w.state,created:new Date().toISOString()});return Response.json({saved:id});}if(b.op!=='turn')throw Error('未知請求');const action=b.text?parse(b.text,s):b.action;if(action.type==='speech'&&b.talkTarget)action.target=b.talkTarget;const next=turn(s,{id:b.requestId,revision:b.revision,action});if(next.revision!==s.revision){const writes=await newEventsWrites(db,s,next);const commands=[db.update(worlds).set({state:JSON.stringify(next),revision:next.revision}).where(and(eq(worlds.id,w.id),eq(worlds.owner,owner),eq(worlds.revision,s.revision))).returning({id:worlds.id}),db.insert(turnCommits).values({world:w.id,request:b.requestId,revision:next.revision,result:JSON.stringify(next.receipts[b.requestId])}),...writes];const [result]=await db.batch(commands);if(!result.length)return Response.json({error:'另一個回合已提交，請重新載入。',conflict:true},{status:409});}return Response.json(visible(next));}catch(e){if(e instanceof Error&&/turn_revision_unique|turn_commits.world, turn_commits.revision/.test(e.message))return Response.json({error:'世界版本已更新，請重新載入。',conflict:true},{status:409});return Response.json({error:e instanceof Error?e.message:'操作失敗'},{status:400});}}
