import WORLD from '../../data/taixu.json' with {type:'json'};
const actors=Object.keys(WORLD.npcs),places=Object.keys(WORLD.places);
const str=(v,n=500)=>typeof v==='string'&&v.trim().length>0&&v.length<=n;
export const EMOTIONS={neutral:'平靜',happy:'喜悅',angry:'不悅',worried:'擔憂',sad:'悲傷',surprised:'驚訝'};
export function validatePlot(p){
 if(!p||!str(p.title,60)||!str(p.premise,250)||!str(p.truth,1600)||!str(p.mechanism,800)||!str(p.past,1200)||!str(p.naturalOutcome,600)||!Array.isArray(p.participants)||!p.participants.length||p.participants.length>4)throw Error('幕後事件檔不完整，未釋出線索');
 for(const a of p.participants)if(!actors.includes(a.id)||!str(a.motive,400)||!str(a.resources,300)||!str(a.knowledge,500))throw Error('事件參與者不合規');
 if(!Array.isArray(p.clues)||p.clues.length<2||p.clues.length>5||!Array.isArray(p.clock)||p.clock.length<2||p.clock.length>5||!Array.isArray(p.branches)||!p.branches.length||p.branches.length>3)throw Error('事件缺少證據、時鐘或可改變的結局');
 const ids=new Set();for(const c of p.clues){if(!/^[a-z][a-z0-9-]{0,35}$/.test(c.id)||ids.has(c.id)||!places.includes(c.place)||!str(c.hint,180)||!str(c.discovery,600)||!str(c.origin,400)||!['evidence','false-lead'].includes(c.type)||!Array.isArray(c.knowers)||c.knowers.some(id=>!actors.includes(id)))throw Error('線索格式不合規');ids.add(c.id);}
 let last=0;for(const c of p.clock){if(!Number.isFinite(c.after)||c.after<=last||c.after>43200||!str(c.event,500)||!str(c.publicReport,350)||!places.includes(c.place)||!Array.isArray(c.knowers)||c.knowers.some(id=>!actors.includes(id)))throw Error('事件時鐘不合規');last=c.after;}
 for(const b of p.branches)if(!/^[a-z][a-z0-9-]{0,35}$/.test(b.id)||!str(b.label,80)||!str(b.outcome,700)||!places.includes(b.place)||!Number.isFinite(b.before)||b.before<=0||b.before>last||!Array.isArray(b.requires)||!b.requires.length||b.requires.some(id=>!ids.has(id)))throw Error('事件分支條件不合規');
 if(new Set(p.branches.map(b=>b.id)).size!==p.branches.length)throw Error('事件分支編號重複');
 // Only enumerated fields survive the boundary. No AI resource/state effects.
 return {title:p.title,premise:p.premise,truth:p.truth,mechanism:p.mechanism,past:p.past,naturalOutcome:p.naturalOutcome,participants:p.participants.map(({id,motive,resources,knowledge})=>({id,motive,resources,knowledge})),clues:p.clues.map(({id,place,hint,discovery,origin,type,knowers})=>({id,place,hint,discovery,origin,type,knowers})),clock:p.clock.map(({after,event,publicReport,place,knowers})=>({after,event,publicReport,place,knowers})),branches:p.branches.map(({id,label,outcome,place,before,requires})=>({id,label,outcome,place,before,requires}))};
}
export function sealPlot(s,proposal,record){const plan=validatePlot(proposal);if(plan.clues[0].place!==s.player.location)throw Error('第一條線索須在目前場景');if((s.chronicles||[]).filter(q=>q.status==='active').length>=2)throw Error('先讓現有事件發展；同時最多兩件背景事件');s.chronicles??=[];const id=`${s.id}:q${s.chronicles.length+1}`;const e=record(s,'plot-sealed','幕後事件真相已固定。',[],{quest:id,plan},'事件建構器',plan.participants.map(a=>a.id));const q={id,sealedEvent:e.id,created:s.time,plan,status:'active',seen:false,found:[],steps:[],history:[],resolution:null};s.chronicles.push(q);return q;}
export function questDeadlines(s){return (s.chronicles||[]).filter(q=>q.status==='active').flatMap(q=>q.plan.clock.filter((_,i)=>!q.steps.includes(i)).map(c=>q.created+c.after));}
export function tickPlots(s,record,message){for(const q of s.chronicles||[]){if(q.status!=='active')continue;for(let i=0;i<q.plan.clock.length;i++){const c=q.plan.clock[i];if(q.steps.includes(i)||q.created+c.after>s.time+1e-8)continue;q.steps.push(i);const e=record(s,'plot-progress',c.event,c.knowers,{quest:q.id,step:i},'當事人親歷',c.knowers);e.location=c.place;q.history.push({time:s.time,event:e.id,description:c.event,kind:'natural'});if(s.player.location===c.place){q.seen=true;record(s,'plot-report',c.publicReport,['player'],{quest:q.id},'現場公告');message(s,'narrator',c.publicReport,'engine',['player']);}}
 if(q.steps.length===q.plan.clock.length){q.status='resolved';q.resolution={kind:'natural',time:s.time,text:q.plan.naturalOutcome};q.history.push({time:s.time,description:q.plan.naturalOutcome,kind:'natural-ending'});record(s,'plot-ended',q.plan.naturalOutcome,q.plan.participants.map(a=>a.id),{quest:q.id},'當事人親歷');}}
}
export function revealPlots(s,record,message){for(const q of s.chronicles||[]){if(q.status==='resolved'&&q.resolution.kind==='natural'&&!q.knownReport&&q.plan.clock.at(-1).place===s.player.location){q.knownReport=q.plan.clock.at(-1).publicReport;record(s,'plot-report',q.knownReport,['player'],{quest:q.id},'現場公告');message(s,'narrator',q.knownReport,'engine',['player']);}const local=q.plan.clues.filter(c=>c.place===s.player.location);if(!local.length||q.seen)continue;q.seen=true;const text=`${q.plan.title}：${q.plan.premise}`;record(s,'plot-clue',text,['player'],{quest:q.id},'現場線索');message(s,'narrator',text,'engine',['player']);}}
export function inspectClue(s,action,record,message){const q=(s.chronicles||[]).find(q=>q.id===action.quest&&q.seen);const c=q?.plan.clues.find(c=>c.id===action.clue);if(!c||c.place!==s.player.location)throw Error('須親自抵達線索所在地');if(q.found.includes(c.id))throw Error('此線索已查閱，可在事件冊重讀');q.found.push(c.id);const e=record(s,'clue-found',c.discovery,['player'],{quest:q.id,clue:c.id},'現場查閱');q.history.push({time:s.time,event:e.id,description:`洛河查閱線索：${c.hint}`,kind:'player'});message(s,'narrator',c.discovery,'engine',['player']);return c.discovery;}
export function intervenePlot(s,action,record,message){const q=(s.chronicles||[]).find(q=>q.id===action.quest&&q.seen);const b=q?.plan.branches.find(b=>b.id===action.branch);if(!b||q.status!=='active'||s.time>=q.created+b.before||s.player.location!==b.place||!b.requires.every(id=>q.found.includes(id)))throw Error('尚未滿足此介入方式的位置、證據或時間條件');q.status='resolved';q.resolution={kind:'player',branch:b.id,time:s.time,text:b.outcome};const e=record(s,'plot-intervention',b.outcome,['player',...q.plan.participants.map(a=>a.id)],{quest:q.id,branch:b.id},'實際介入');q.history.push({time:s.time,event:e.id,description:b.outcome,kind:'player-ending'});message(s,'narrator',b.outcome,'engine',['player']);return b.outcome;}
export function visiblePlots(s){return (s.chronicles||[]).filter(q=>q.seen).map(q=>({id:q.id,title:q.plan.title,premise:q.plan.premise,status:q.status==='resolved'&&q.resolution.kind==='natural'?(q.knownReport?'已結束':'進行中／待查證'):q.status==='resolved'?'已介入':'進行中',clues:q.plan.clues.map(c=>({id:c.id,place:c.place,hint:c.hint,found:q.found.includes(c.id),discovery:q.found.includes(c.id)?c.discovery:null})),branches:q.status==='active'?q.plan.branches.filter(b=>b.requires.every(id=>q.found.includes(id))&&s.time<q.created+b.before).map(b=>({id:b.id,label:b.label,place:b.place,due:q.created+b.before})):[],resolution:q.resolution?.kind==='player'?q.resolution.text:q.knownReport||null}));}
export function admitLore(s,proposals,record,message,present){const result=[];for(const p of (Array.isArray(proposals)?proposals:[]).slice(0,1)){if(!p||!present.includes(p.actor)||!['preference','habit','anecdote'].includes(p.kind)||!str(p.key,40)||!str(p.value,280))throw Error('人物補寫格式不符');if(/洛河|小師妹|風痕|血統|殺死|滅門|突破|失蹤|陰謀|神器|前世|救過你/.test(p.value))throw Error('人物補寫越過日常往事範圍');s.lore??=[];const existing=s.lore.find(f=>f.actor===p.actor&&f.key===p.key);if(existing){if(existing.value!==p.value)throw Error('人物設定已固定，不可覆寫');const audience=['player',...present];const e=record(s,'npc-lore-recalled',`${WORLD.npcs[p.actor].name}再次談起：「${existing.value}」`,audience,{actor:p.actor,lore:existing.id},'本人重述既有設定');e.links=[existing.id];existing.knowers=[...new Set([...existing.knowers,...audience])];message(s,p.actor,existing.value,'dialogue',audience,e.id);continue;}if(s.lore.filter(f=>f.actor===p.actor).length>=30)continue;const audience=['player',...present];const e=record(s,'npc-lore',`${WORLD.npcs[p.actor].name}談起自己：「${p.value}」`,audience,{actor:p.actor,kind:p.kind,key:p.key,value:p.value},'NPC 自述；已採用的日常設定');s.lore.push({id:e.id,actor:p.actor,kind:p.kind,key:p.key,value:p.value,time:s.time,knowers:audience});const m=message(s,p.actor,p.value,'dialogue',audience,e.id);m.presentation={expression:'neutral',emotion:'neutral',reason:'談起自己的日常往事'};result.push(e);}return result;}
