import WORLD from '../../data/taixu.json' with {type:'json'};
import PERSONAS from '../../data/story-npcs.json' with {type:'json'};
import {CORE_RULES} from './core-rules.mjs';
const copy=x=>JSON.parse(JSON.stringify(x));
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const str=(v,max=400)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw Error('世界事件文字格式不符');return v.trim()};
const npc=id=>{if(!Object.hasOwn(PERSONAS,id))throw Error('事件引用不存在的人物');return id};
const place=id=>{if(!Object.hasOwn(WORLD.places,id))throw Error('事件引用未開放地點');return id};
const id=v=>{if(typeof v!=='string'||!/^[-a-z0-9]{1,40}$/.test(v))throw Error('事件欄位 ID 不符');return v};
const list=(v,min,max)=>{if(!Array.isArray(v)||v.length<min||v.length>max)throw Error('事件清單長度不符');return v};
export function ensureLiving(s){s.living??={version:1,events:[],nextPlanAt:s.time,sequence:0};return s.living;}
export function canPlan(s){return (!s.living||s.time>=s.living.nextPlanAt)&&!(s.living?.events||[]).some(e=>e.status==='active');}
export function directorContext(s){return {time:s.time,places:WORLD.places,npcs:Object.entries(s.npcs).map(([id,n])=>({id,...WORLD.npcs[id],persona:PERSONAS[id],current:{realm:n.realm,location:n.location,activity:n.activity,health:n.health,goal:n.goal||PERSONAS[id].goal}})),recentEvents:(s.living?.events||[]).slice(-4).map(e=>({title:e.dossier.title,status:e.status,truth:e.dossier.cause})),constraints:'只創造從此刻開始、與既有目標一致的新事件。不得補造既有大事、家世、風痕、古城或其他世界線。限已存在人物與地點。'};}
export const DIRECTOR_PROMPT=CORE_RULES+`\n你只建立後台事件檔，不寫給玩家看。先規劃一項小到中等、可以不介入的生活／修行／宗門事件，不要每次危機。資料中沒有的歷史不能補造；事件從現在開始。不要看玩家猜測改真相。JSON 格式：
{"title":"短題","cause":"從此刻發生的真正起因","closure":"收束條件與後果","hook":{"place":"地點ID","text":"現場可見的公告或痕跡，不洩露私密真相"},"actors":[{"id":"NPC ID","motive":"私人動機","goal":"本事件目標"}],"facts":[{"id":"fact-id","text":"固定事實","knowers":["NPC ID"]}],"evidence":[{"id":"clue-id","fact":"fact-id","place":"地點ID","after":0,"expires":2880,"difficulty":30}],"beliefs":[{"actor":"NPC ID","claim":"可能錯的推測","basis":"fact-id","status":"suspected或mistaken"}],"steps":[{"after":120,"actor":"NPC ID","place":"地點ID","activity":"自主行動","difficulty":35,"success":"成功結果","failure":"受阻或未完成的結果","public":false,"peer":"另一NPC ID或null"},{"after":2880,"actor":"NPC ID","place":"地點ID","activity":"後續與收束","difficulty":40,"success":"結果","failure":"結果","public":true}]}
2–4 facts；1–4 evidence；1–4 actors；0–4 beliefs（每項必須有該人已知的basis）；2–4 steps，以 after 分鐘遞增，第一步至少120分鐘，最終48小時至7日內。每個步驟只是在指定地點嘗試自己的活動；不保證到場或成功，failure須可涵蓋行動受阻。success/failure只描述該活動結果，不得包含殺人、重傷、境界突破、贈送物品、強迫主角或新幕後人物。public只代表在該地可見公告，不代表所有角色立刻知道。難度0–100。不創造新NPC、地點、數值效果；效果由引擎處理。所有文字精煉，每欄不超過200字。`;
export function validateDossier(raw){
 const actors=list(raw?.actors,1,4).map(a=>({id:npc(a.id),motive:str(a.motive,200),goal:str(a.goal,200)}));
 if(new Set(actors.map(a=>a.id)).size!==actors.length)throw Error('事件人物重複');
 const facts=list(raw.facts,2,4).map(f=>({id:id(f.id),text:str(f.text,200),knowers:[...new Set(list(f.knowers,0,4).map(npc))]}));
 if(new Set(facts.map(f=>f.id)).size!==facts.length)throw Error('事件事實 ID 重複');
 const evidence=list(raw.evidence,1,4).map(e=>{if(!facts.some(f=>f.id===e.fact))throw Error('線索沒有固定真相來源');if(!Number.isFinite(e.after)||!Number.isFinite(e.expires)||e.after<0||e.expires<=e.after||e.expires>10080)throw Error('線索時限不符');if(!Number.isFinite(e.difficulty)||e.difficulty<0||e.difficulty>100)throw Error('線索難度不符');return{id:id(e.id),fact:e.fact,place:place(e.place),after:e.after,expires:e.expires,difficulty:e.difficulty}});
 if(new Set(evidence.map(e=>e.id)).size!==evidence.length)throw Error('線索 ID 重複');
 const beliefs=list(raw.beliefs||[],0,4).map(b=>{npc(b.actor);if(!['suspected','mistaken'].includes(b.status)||!facts.some(f=>f.id===b.basis&&f.knowers.includes(b.actor)))throw Error('NPC 推測缺少本人已知依據');return{actor:b.actor,claim:str(b.claim,200),basis:b.basis,status:b.status}});
 const steps=list(raw.steps,2,4).map(st=>{if(!actors.some(a=>a.id===st.actor)||!Number.isFinite(st.after)||st.after<120||st.after>10080||!Number.isFinite(st.difficulty)||st.difficulty<0||st.difficulty>100||typeof st.public!=='boolean')throw Error('事件時間線或行動者不符');return{after:st.after,actor:st.actor,place:place(st.place),activity:str(st.activity,120),difficulty:st.difficulty,success:str(st.success,200),failure:str(st.failure,200),public:st.public,peer:st.peer==null?null:npc(st.peer)}});
 if(steps.at(-1).after<2880||steps.some((x,i)=>i&&x.after<=steps[i-1].after))throw Error('事件時序不符');
 return {version:1,title:str(raw.title,60),cause:str(raw.cause,200),closure:str(raw.closure,200),hook:{place:place(raw.hook?.place),text:str(raw.hook?.text,200)},actors,facts,evidence,beliefs,steps};
}
export function sealLiving(s,raw,record){const dossier=validateDossier(raw),living=ensureLiving(s);if(living.events.some(e=>e.status==='active'))throw Error('尚有自主事件未收束');const eid=`living-${++living.sequence}`;
 const event={id:eid,created:s.time,dossier,seal:JSON.stringify(dossier),status:'active',cursor:0,influence:0,actual:[],interventions:[],acquired:{},attempts:{},observed:[],notices:[]};living.events.push(event);living.nextPlanAt=s.time+4320;
 for(const [n,actor]of Object.entries(s.npcs)){actor.beliefs??=[];actor.peerRelations??={};actor.currentGoal??=PERSONAS[n].goal;}
 for(const a of dossier.actors){s.npcs[a.id].currentGoal=a.goal;}
 const e=record(s,'event-sealed','一份自主事件檔已在探索前封存。',[],{incident:eid},'世界規劃引擎',dossier.actors.map(a=>a.id));event.sealedEvent=e.id;
 for(const f of dossier.facts){const e=record(s,'private-fact',f.text,f.knowers,{incident:eid,fact:f.id},'事件成立時已掌握的事實',f.knowers);for(const who of f.knowers)acquire(event,who,f.id,e.id,s.time);}
 for(const b of dossier.beliefs)s.npcs[b.actor].beliefs.push({...b,event:eid,source:event.acquired[b.actor][b.basis].source,time:s.time});
 observeLiving(s,record);return event;
}
function acquire(e,who,fact,source,time){e.acquired[who]??={};e.acquired[who][fact]={source,time};}
export function assertLivingSeals(s){for(const e of s.living?.events||[])if(e.seal!==JSON.stringify(e.dossier))throw Error('自主事件真相與封存版本不符，未提交回合');}
export function livingDeadlines(s){return(s.living?.events||[]).filter(e=>e.status==='active').flatMap(e=>e.dossier.steps.slice(e.cursor).flatMap(st=>[e.created+st.after-90,e.created+st.after])).filter(t=>t>s.time+1e-8);}
export function livingTask(s,id,time=s.time){for(const e of s.living?.events||[]){if(e.status!=='active')continue;const st=e.dossier.steps[e.cursor];if(st&&st.actor===id&&time>=e.created+st.after-90&&time<=e.created+st.after)return [0,st.place,st.activity];}return null;}
const level=r=>['鍛體','聚氣','築基','金丹','元嬰','化神','洞虛','合道','渡劫'].findIndex(x=>r?.startsWith(x));
export function check(s,{actor='player',difficulty=50,preparation=0,information=0,opponent=null}={}){const a=actor==='player'?s.player:s.npcs[actor];if(!a)throw Error('判定角色不存在');const power=level(a.realm),other=opponent?level((opponent==='player'?s.player:s.npcs[opponent])?.realm):null;const impossible=other!=null&&other-power>=2;const ability=power*7+Math.min(10,Math.log2(1+(a.trainingHours||a.trainingMinutes/60||0)));const chance=impossible?0:clamp(58+ability+(a.health-100)*.4-(a.fatigue||0)*.3+clamp(preparation,-20,20)+clamp(information,0,15)-difficulty*.6,3,95);s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;const roll=s.seed/4294967296*100;return{success:roll<chance,chance,roll,impossible,actor,difficulty,preparation,information,ability};}
export function tickLiving(s,record){assertLivingSeals(s);for(const e of s.living?.events||[]){if(e.status!=='active')continue;while(e.cursor<e.dossier.steps.length){const st=e.dossier.steps[e.cursor],due=e.created+st.after;if(due>s.time)break;const n=s.npcs[st.actor],available=!n.travel&&n.location===st.place,judgement=check(s,{actor:st.actor,difficulty:st.difficulty,preparation:e.influence,information:Object.keys(e.acquired[st.actor]||{}).length*3});const success=available&&judgement.success;
 if(available){for(const clue of e.dossier.evidence){if(clue.place!==st.place||s.time<e.created+clue.after||s.time>=e.created+clue.expires||e.acquired[st.actor]?.[clue.fact])continue;const attemptKey=st.actor+':'+clue.id;if(e.attempts[attemptKey])continue;e.attempts[attemptKey]=true;const investigation=check(s,{actor:st.actor,difficulty:clue.difficulty,information:Object.keys(e.acquired[st.actor]||{}).length*3});if(investigation.success){const fact=e.dossier.facts.find(f=>f.id===clue.fact);const learned=record(s,'private-evidence',fact.text,[st.actor],{incident:e.id,evidence:clue.id},'NPC 在現場自主查證',[st.actor]);learned.location=st.place;acquire(e,st.actor,fact.id,learned.id,s.time);}}}
 const text=success?st.success:st.failure,knowers=[st.actor];if(available){for(const [id,p]of Object.entries(s.npcs))if(!p.travel&&p.location===st.place&&!knowers.includes(id))knowers.push(id);if(s.player.location===st.place)knowers.push('player');}
 const ev=record(s,'autonomous-action',text,knowers,{incident:e.id,step:e.cursor,success},'自主行動結算',[st.actor]);ev.location=st.place;e.actual.push({event:ev.id,time:s.time,actor:st.actor,content:text,success,judgement:{...judgement,available}});
 n.insight+=success?.2:.05;n.emotionalState=success?'平靜':'不悅';n.emotionUntil=s.time+120;
 if(st.peer&&knowers.includes(st.peer)){n.peerRelations??={};const r=n.peerRelations[st.peer]??={trust:20,respect:20,closeness:10,conflict:0,history:[]};r.trust=clamp(r.trust+(success?2:-1),0,100);r.history.push({event:ev.id,result:success?'合作有所進展':'行動受阻'});}
 if(st.public)e.notices.push({place:st.place,text,source:ev.id,readBy:[]});e.cursor++;
 if(e.cursor===e.dossier.steps.length){e.status='closed';e.closedAt=s.time;e.outcome=success?'completed':'setback';s.living.nextPlanAt=Math.max(s.living.nextPlanAt,s.time+1440);for(const a of e.dossier.actors)s.npcs[a.id].currentGoal=PERSONAS[a.id].goal;}
 }}observeLiving(s,record);}
export function observeLiving(s,record){for(const e of s.living?.events||[]){const at=s.player.location;if(e.dossier.hook.place===at&&!e.observed.includes('player')){const ev=record(s,'event-hook',e.dossier.hook.text,['player'],{incident:e.id},'親自看見現場公告');e.observed.push('player');e.hookEvent=ev.id;}
 for(const n of e.notices){for(const who of ['player',...Object.keys(s.npcs)]){const a=who==='player'?s.player:s.npcs[who];if(a.travel||a.location!==n.place||n.readBy.includes(who))continue;const ev=record(s,'notice',n.text,[who],{incident:e.id,origin:n.source},'現場公告',[who]);ev.location=n.place;n.readBy.push(who);}}
 }}
export function livingActions(s){const actions=[];for(const e of s.living?.events||[]){if(!e.observed.includes('player'))continue;for(const c of e.dossier.evidence){if(s.player.location===c.place&&s.time>=e.created+c.after&&s.time<e.created+c.expires&&!e.acquired.player?.[c.fact]&&!e.attempts['player:'+c.id])actions.push({event:e.id,operation:'investigate',evidence:c.id,label:'查證：'+e.dossier.title});}const st=e.dossier.steps[e.cursor];if(e.status==='active'&&st&&s.player.location===st.place&&s.time<e.created+st.after-15){for(const operation of ['aid','obstruct'])if(!e.attempts['player:'+operation])actions.push({event:e.id,operation,label:(operation==='aid'?'協助：':'阻止：')+e.dossier.title});}}
 return actions;}
export function interveneLiving(s,a,record){if(!livingActions(s).some(x=>x.event===a.event&&x.operation===a.operation&&x.evidence===a.evidence))throw Error('目前不符合這項事件行動的條件');const e=s.living.events.find(e=>e.id===a.event);let result,text;
 if(a.operation==='investigate'){const c=e.dossier.evidence.find(c=>c.id===a.evidence);result=check(s,{difficulty:c.difficulty,information:Object.keys(e.acquired.player||{}).length*3});e.attempts['player:'+c.id]=true;if(result.success){const f=e.dossier.facts.find(f=>f.id===c.fact);text=f.text;const ev=record(s,'evidence',text,['player'],{incident:e.id,evidence:c.id},'現場查證');acquire(e,'player',f.id,ev.id,s.time);}else text='查證未取得足以確認的證據；這不代表任何猜測已被證實。';}
 else{result=check(s,{difficulty:45,information:Object.keys(e.acquired.player||{}).length*4});e.attempts['player:'+a.operation]=true;if(result.success)e.influence=clamp(e.influence+(a.operation==='aid'?15:-15),-20,20);text=result.success?'你的介入改變了這次行動的條件，最終結果仍待結算。':'你的介入未能改變目前條件。';s.player.health=Math.max(0,s.player.health-(result.success?0:2));}
 const ev=record(s,'event-intervention',text,['player',...Object.keys(s.npcs).filter(id=>!s.npcs[id].travel&&s.npcs[id].location===s.player.location)],{incident:e.id,operation:a.operation,success:result.success},'行動判定');e.interventions.push({event:ev.id,time:s.time,operation:a.operation,result});return text;
}
export function livingKnown(s,actors){const events=[];for(const e of s.living?.events||[]){for(const f of e.dossier.facts){if(actors.every(id=>e.acquired[id]?.[f.id]))events.push({id:e.acquired[actors[0]][f.id].source,content:f.text,source:'已查證的事件證據',knowers:actors,confirmed:true});}}return events;}
