import {archiveDossier,incidentActions,intervene} from './incidents.mjs';
import WORLD from '../../data/taixu.json' with {type:'json'};
import {personalityOf,editPersonality} from './personality.mjs';
import SCENES from '../../data/scenes.json' with {type:'json'};
import PERSONAS from '../../data/story-npcs.json' with {type:'json'};
import {route} from '../game/engine.mjs';
export {PERSONAS};
export const PLACES=Object.fromEntries(Object.entries(WORLD.places).map(([id,p])=>[id,{...p,description:SCENES[id]?.ambience||p.description}]));
export const clone=x=>JSON.parse(JSON.stringify(x));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export function record(s,type,content,knowers=['player'],changes={},source='親身經歷',actors=knowers){const e={id:`${s.id}:e${++s.eventSeq}`,timeline:s.id,time:s.time,recordedAt:new Date().toISOString(),type,content,actors,location:s.player.location,source,confirmed:true,knowers:[...new Set(knowers)],changes,links:[]};s.events.push(e);return e;}
export function message(s,speaker,content,kind='dialogue',audience=['player'],event=null){const m={id:`${s.id}:m${++s.messageSeq}`,seq:s.messageSeq,minute:s.time,location:s.player.location,speaker,kind,content,audience:[...new Set(audience)],event};s.messages.push(m);return m;}
export function schedule(id,time){const hour=(time%1440)/60;return PERSONAS[id].daily.filter(row=>row[0]<=hour).at(-1)||PERSONAS[id].daily[0];}
export function initialStory(id){const s={mode:'story-v1',version:1,id,revision:0,time:17*60,eventSeq:0,messageSeq:0,events:[],messages:[],seed:1731,player:{name:'洛河',age:15,initialAge:15,realm:'聚氣初期',health:100,progress:0,trainingMinutes:0,injuries:[],money:10,items:{木劍:1,療傷丹:1},location:'home'},npcs:{},promises:[],threads:{shen:{topic:'庭院初遇',openQuestion:'今日過得如何？'}},scene:{location:'home',target:'shen',topic:'庭院初遇',openQuestion:'今日過得如何？',questionSpeaker:'shen'},contacts:{},lastSeen:{},truth:{id:'archive-restoration',sealedAt:0,cause:'舊卷已送往主峰修繕，三十日後歸還',evidence:['修繕收據','庫房登記'],naturalOutcome:'第三十日公開歸還舊卷',dossier:archiveDossier()},incident:{actual:[],interventions:[]},worldPlans:[{id:'repair',due:30*1440+600,done:false},{id:'jiang-commission',due:14*1440+600,done:false}]};
for(const [npc,base]of Object.entries(WORLD.npcs)){const plan=schedule(npc,s.time);s.npcs[npc]={id:npc,realm:base.realm,location:plan[1],travel:null,activity:plan[2],health:100,fatigue:0,trainingHours:0,money:40,workHours:0,insight:0,breakthroughs:0,emotionalState:'平靜',emotionUntil:0,relations:{trust:20,respect:20,closeness:10,caution:10,interest:0,grievance:0},reliability:{kept:0,broken:0},judgement:[],conflicts:[],relationBudget:{day:0,used:0},lastPublicMilestone:0};}
const e=record(s,'enroll','洛河已以純風靈根拜入棲風峰，開始入門後的生活。',['player','shen','yan'],{},'宗門入門登記');
message(s,'narrator','晚課已散。棲風峰庭院裡茶香微暖，沈滄月放下手中的卷宗，抬眼望向你。','opening',['player','shen'],e.id);
message(s,'shen','今日過得如何？','opening',['player','shen']);observe(s);return s;}
export function present(s){return Object.keys(s.npcs).filter(id=>s.npcs[id].location===s.player.location&&!s.npcs[id].travel);}
export function observe(s){for(const id of present(s)){s.contacts[id]={id,name:WORLD.npcs[id].name,role:WORLD.npcs[id].role,realm:s.npcs[id].realm,lastLocation:s.player.location,lastSeen:s.time};const n=s.npcs[id],last=s.lastSeen[id];if(last&&last.realm!==n.realm)record(s,'growth-observed',`再次相見時，你得知${WORLD.npcs[id].name}的修為已至${n.realm}。`,['player',id],{realm:n.realm},'當面交流');s.lastSeen[id]={realm:n.realm,time:s.time};}}
function relation(s,id,changes,eventId){const n=s.npcs[id],day=Math.floor(s.time/1440);if(n.relationBudget.day!==day)n.relationBudget={day,used:0};const weight=Object.values(changes).reduce((a,b)=>a+Math.abs(b),0),factor=Math.min(1,Math.max(0,6-n.relationBudget.used)/weight);changes=Object.fromEntries(Object.entries(changes).map(([k,v])=>[k,v*factor]));n.relationBudget.used+=weight*factor;for(const [k,v]of Object.entries(changes))n.relations[k]=clamp(n.relations[k]+v,0,100);n.judgement.push({event:eventId,time:s.time,changes});if(n.judgement.length>40)n.judgement.shift();}
function completePromises(s){for(const p of s.promises){if(p.status!=='active')continue;const done=(p.kind==='visit'&&s.player.location===p.place&&present(s).includes(p.to))||(p.kind==='train'&&s.player.trainingMinutes-p.trainingAtStart>=p.requiredMinutes);if(done&&s.time<=p.due){p.status='fulfilled';p.resolvedAt=s.time;const knows=p.kind==='visit'?['player',p.to]:['player'];const e=record(s,'promise-fulfilled',`你履行了承諾：${p.description}`,knows,{promise:p.id},'引擎核實');p.resultEvent=e.id;if(p.kind==='visit'){s.npcs[p.to].reliability.kept++;relation(s,p.to,{trust:3,respect:1,grievance:-1},e.id);p.knownByRecipient=true;}}}}
function expirePromises(s){for(const p of s.promises){if(p.status==='active'&&p.due<=s.time){p.status='missed';p.resolvedAt=s.time;const witnessed=p.kind==='visit'&&s.npcs[p.to].location===p.place&&!s.npcs[p.to].travel;const knows=witnessed?['player',p.to]:['player'];const e=record(s,'promise-missed',`約定期限已到，你未完成：${p.description}`,knows,{promise:p.id},'期限結算');if(witnessed){p.knownByRecipient=true;s.npcs[p.to].reliability.broken++;s.npcs[p.to].conflicts.push({id:p.id,cause:e.id,status:'unresolved'});relation(s,p.to,{trust:-5,caution:3,grievance:2},e.id);s.npcs[p.to].emotionalState='失望';s.npcs[p.to].emotionUntil=s.time+180;}}}}
function random(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
function executePlans(s){for(const p of s.worldPlans){if(p.done||p.due>s.time)continue;p.done=true;if(p.id==='repair'){const completion=record(s,'world-public','藏經樓的舊卷修繕完成，宗門公布歸還登記。',Object.keys(s.npcs),{plan:p.id},'宗門公告',Object.keys(s.npcs));if(s.incident)s.incident.actual.push({event:completion.id,time:s.time,content:completion.content});if(s.player.location==='library')record(s,'news','你在藏經樓看見舊卷歸還的公告。',['player'],{},'現場公告');}if(p.id==='jiang-commission'){const success=random(s)>.25,n=s.npcs.jiang;n.money+=success?15:3;n.insight+=success?2:1;record(s,'npc-plan',success?'江離完成了一項宗門委託，取得報酬與經驗。':'江離的委託遇到阻礙，提早撤回並整理教訓。',['jiang'],{money:success?15:3},'江離親歷',['jiang']).location=n.location;}}}
export function advanceStory(s,minutes,{training=false,stopAtDeadline=true}={}){if(!Number.isFinite(minutes)||minutes<=0||minutes>5*360*1440)throw Error('時間須大於零，且不超過五年。');const start=s.time,end=s.time+minutes;let interrupted=false;
while(s.time<end-1e-8){const day=Math.floor(s.time/1440),boundaries=[...new Set(Object.values(PERSONAS).flatMap(p=>p.daily.map(r=>day*1440+r[0]*60)))];boundaries.push((day+1)*1440);const deadlines=s.promises.filter(p=>p.status==='active'&&p.due>s.time).map(p=>p.due);const trainingDue=training?s.promises.filter(p=>p.status==='active'&&p.kind==='train').map(p=>s.time+Math.max(0,p.requiredMinutes-(s.player.trainingMinutes-p.trainingAtStart))).filter(t=>t>s.time+1e-8):[];const next=Math.min(end,...trainingDue,...boundaries.filter(t=>t>s.time+1e-8),...Object.values(s.npcs).filter(n=>n.travel).map(n=>n.travel.arrive),...deadlines,...s.worldPlans.filter(p=>!p.done&&p.due>s.time).map(p=>p.due));const dt=next-s.time;if(dt<=0)throw Error('時間排程無法前進');
 if(training){s.player.trainingMinutes+=dt;s.player.progress=Math.min(100,s.player.progress+dt/1440*.12);}
 s.player.injuries=s.player.injuries.map(i=>({...i,remaining:Math.max(0,i.remaining-dt)})).filter(i=>i.remaining>0);s.player.health=Math.min(100,s.player.health+dt/1440*5);
 for(const [id,n]of Object.entries(s.npcs)){if(n.travel)continue;const activity=schedule(id,s.time)[2];n.activity=activity;if(activity==='修行'&&n.health>=60&&n.fatigue<80)n.trainingHours+=dt/60*PERSONAS[id].trainingRate;if(activity==='休息')n.fatigue=Math.max(0,n.fatigue-dt/60*3);else n.fatigue=Math.min(100,n.fatigue+dt/60*.35);if(/事務|授課|委託|維護|校訂/.test(activity)){n.workHours+=dt/60;n.insight+=dt/60*.002;}n.health=Math.min(100,n.health+dt/1440*3);}
 const oldMonth=Math.floor(s.time/43200);s.time=next;s.player.age=(s.player.initialAge||15)+Math.floor((s.time-1020)/518400);const monthCount=Math.floor(s.time/43200)-oldMonth;if(monthCount){s.player.money+=3*monthCount;record(s,'income',`宗門月例入帳 ${3*monthCount} 枚靈石。`,['player'],{money:3*monthCount},'宗門帳房');for(const n of Object.values(s.npcs))n.money+=monthCount*8;}
 for(const [id,n]of Object.entries(s.npcs)){if(n.travel&&n.travel.arrive<=s.time+1e-8){n.location=n.travel.to;n.travel=null;}if(n.emotionUntil<=s.time)n.emotionalState='平靜';const plan=schedule(id,s.time);n.activity=n.travel?'途中':plan[2];if(!n.travel&&n.location!==plan[1])n.travel={from:n.location,to:plan[1],depart:s.time,arrive:s.time+route(n.location,plan[1]).minutes};const p=PERSONAS[id];if(!n.breakthroughs&&n.trainingHours>=p.threshold&&n.money>=p.breakthroughCost&&n.insight>=3&&n.health>=80&&!n.travel&&n.activity==='修行'){n.money-=p.breakthroughCost;n.realm=p.nextRealm;n.breakthroughs++;record(s,'npc-growth',`${WORLD.npcs[id].name}經過長期修行與準備，修為進至${n.realm}。`,[id],{realm:n.realm,cost:p.breakthroughCost},'本人親歷',[id]).location=n.location;}}
 executePlans(s);completePromises(s);const due=deadlines.some(t=>Math.abs(t-s.time)<1e-8);expirePromises(s);if(due&&stopAtDeadline&&s.time<end){interrupted=true;break;}}
 if(minutes>=1)record(s,'time',`${training?'修行':'時間流逝'} ${Math.round((s.time-start)*10)/10} 分鐘${interrupted?'，在約定期限中斷':''}。`,['player'],{elapsed:s.time-start,interrupted});return {elapsed:s.time-start,interrupted};}
export function resolveAction(previous,action,raw=''){const s=clone(previous);s.events=[];s.messages=[];const before=present(s);let summary='',target=s.scene.target;if(action?.kind==='gesture'&&action.target)s.scene.target=action.target;
if(!action||!['speak','continue','thought','move','train','wait','consume','observe','promise','report-promise','gesture','system','remember','personality-edit','incident'].includes(action.kind))throw Error('此行動尚未實作，沒有改動存檔。');
if(action.kind==='speak'||action.kind==='continue'){if(action.target)target=action.target;if(!target||!before.includes(target))throw Error('對方目前不在場，請先到能見到對方的地點。');s.scene.target=target;const content=raw||'繼續';if(action.kind==='speak'){const e=record(s,'speech',`洛河說：「${content}」`,['player',...before],{assertions:'unverified'},'當面聽見');message(s,'player',content,'dialogue',['player',...before],e.id);}else message(s,'narrator','片刻過去。','continuation',['player',...before]);advanceStory(s,Math.min(1,Math.max(.08,content.length/240)),{stopAtDeadline:false});summary='玩家說完話，等待回應。';}
if(action.kind==='incident'){summary=intervene(s,action.operation,record);advanceStory(s,1);}
if(action.kind==='personality-edit'){const e=record(s,'personality-edit','開發者調整了此世界線的主角演出設定。',['player'],{operation:action.operation,trait:action.trait||null},'開發者明確設定');editPersonality(s,action,e.id);summary='主角演出設定已更新，過去事件保持原狀。';}
if(action.kind==='remember'){const m=action.sourceMessage;if(!m||!m.audience?.includes('player'))throw Error('沒有可保留的已知對話');record(s,'personal-memory',`${m.speaker==='player'?'洛河':WORLD.npcs[m.speaker]?.name||'場景'}曾說：「${m.content}」`,m.audience,{message:m.id,spokenAt:m.minute,assertions:'unverified'},'對話原文');summary='這段話已保留為重要記憶；只有當時在場的知情者可取用。';}
if(action.kind==='system'){summary=`目前為第 ${Math.floor(s.time/1440)+1} 日，位於${PLACES[s.player.location].name}。洛河修為${s.player.realm}，靈石 ${s.player.money} 枚，健康 ${s.player.health.toFixed(0)}，未完成承諾 ${s.promises.filter(p=>p.status==='active').length} 件。系統查詢不推進時間。`;}
if(action.kind==='gesture'){const actions={sit:'你在現場找了個位置坐下。',stand:'你站起身。',bow:'你向在場的人行禮。',smile:'你露出一個笑容。',silence:'你沉默了片刻。',tea:'你端起庭院桌上的茶，喝了一口。','put-sword':'你把木劍放在身旁。'};if(!actions[action.code])throw Error('此動作尚未支援');if(action.code==='tea'&&s.player.location!=='home')throw Error('此處沒有已確認的茶具');if(action.code==='put-sword')throw Error('物品放置與拾取尚未完成，未變更木劍所在。');const e=record(s,'gesture',actions[action.code],['player',...before]);message(s,'player',raw||actions[action.code],'action',['player',...before],e.id);advanceStory(s,.25,{stopAtDeadline:false});summary=actions[action.code];}
if(action.kind==='thought'){message(s,'player',raw,'thought',['player']);summary='這段內心想法沒有說出口。';}
if(action.kind==='move'){if(!PLACES[action.place])throw Error('地點尚未開放');const from=s.player.location,minutes=route(from,action.place).minutes;if(!minutes){summary='你已在這裡。';}else{const r=advanceStory(s,minutes);if(!r.interrupted){s.player.location=action.place;record(s,'move',`你從${PLACES[from].name}前往${PLACES[action.place].name}。`,['player'],{from,to:action.place},'親身經歷');s.scene={location:action.place,target:null,topic:'抵達',openQuestion:null,questionSpeaker:null};summary=PLACES[action.place].description;}else summary='約定期限已到，旅程暫停；你仍在出發地。';}}
if(action.kind==='train'||action.kind==='wait'){if(action.kind==='train'&&!['home','room','court'].includes(s.player.location))throw Error('此處不適合修行');const r=advanceStory(s,action.minutes,{training:action.kind==='train'});summary=`${action.kind==='train'?'修行':'等待'}結束，經過 ${Math.round(r.elapsed)} 分鐘。${r.interrupted?'約定期限已到，快進中斷。':''}`;}
if(action.kind==='consume'){if(action.item!=='療傷丹'||s.player.items.療傷丹<1)throw Error('行囊沒有可用的療傷丹');s.player.items.療傷丹--;s.player.health=Math.min(100,s.player.health+20);for(const i of s.player.injuries)i.remaining=Math.max(0,i.remaining-1440);s.player.injuries=s.player.injuries.filter(i=>i.remaining>0);record(s,'consume','你服用一枚療傷丹。',['player',...before],{item:'療傷丹',quantity:-1});summary='丹藥已消耗，傷勢依藥效結算。';}
if(action.kind==='promise'){if(!before.includes(action.to))throw Error('請當面向對方許下約定');if(!['visit','train'].includes(action.promiseKind))throw Error('此類承諾尚未支援客觀驗證');if(!Number.isFinite(action.afterMinutes)||action.afterMinutes<1||action.afterMinutes>518400)throw Error('承諾期限須在一年內');if(action.promiseKind==='visit'&&(!PLACES[action.place]||action.place===s.player.location))throw Error('赴約需指定另一個已知地點');if(action.promiseKind==='train'&&(!Number.isFinite(action.requiredMinutes)||action.requiredMinutes<1||action.requiredMinutes>43200))throw Error('修行承諾需指定有效時間');const description=action.promiseKind==='visit'?`在期限前到${PLACES[action.place].name}與${WORLD.npcs[action.to].name}見面`:`在期限前完成 ${action.requiredMinutes} 分鐘修行`;const p={id:`${s.id}:p${s.promises.length+1}`,to:action.to,kind:action.promiseKind,place:action.place||null,requiredMinutes:action.requiredMinutes||0,description,created:s.time,due:s.time+action.afterMinutes,status:'active',trainingAtStart:s.player.trainingMinutes};s.promises.push(p);const e=record(s,'promise',`洛河承諾：${description}。`,['player',action.to],{promise:p.id,due:p.due},'當面約定');message(s,'player',`我答應：${description}。`,'promise',['player',action.to],e.id);s.scene.target=action.to;summary=`承諾已登記，期限為第 ${Math.floor(p.due/1440)+1} 日 ${Math.floor(p.due%1440/60)} 時。`;}
if(action.kind==='report-promise'){const p=s.promises.find(p=>p.id===action.promise);if(!p||p.status!=='fulfilled'||p.kind!=='train')throw Error('沒有可回報的修行承諾');if(!before.includes(p.to))throw Error('對方不在場');if(p.knownByRecipient)throw Error('已回報此承諾');p.knownByRecipient=true;const e=record(s,'promise-report',`洛河向${WORLD.npcs[p.to].name}回報已完成約定修行。`,['player',p.to],{promise:p.id,claim:'player-report'},'玩家當面回報');s.npcs[p.to].reliability.kept++;relation(s,p.to,{trust:1,respect:1},e.id);summary='對方收到你的回報；這是回報來源，不是對方親眼看見整段修行。';}
if(action.kind==='observe'){summary=PLACES[s.player.location].description;if(s.player.location==='library'&&s.worldPlans.find(p=>p.id==='repair').done){record(s,'news','你查閱公告，確認舊卷已修繕歸還。',['player'],{},'藏經樓公開登記');summary+=' 公告記載：舊卷已修繕歸還。';}}
completePromises(s);observe(s);if(s.scene.target&&!present(s).includes(s.scene.target)){s.scene.target=null;s.scene.openQuestion=null;s.scene.questionSpeaker=null;summary+=' 對方已按自己的行程離開。';}
if(!['speak','continue','gesture'].includes(action.kind)||(!s.scene.target&&['speak','continue','gesture'].includes(action.kind)))message(s,'narrator',summary,'engine',['player']);s.revision++;return {state:s,summary,action};}
export function npcContext(s,id,memories=[],transcript=[]){if(!present(s).includes(id))throw Error('NPC 不在場');const n=s.npcs[id];return {npc:{id,...WORLD.npcs[id],...PERSONAS[id],state:{realm:n.realm,health:n.health,fatigue:n.fatigue,activity:n.activity,emotion:n.emotionalState,relations:n.relations,reliability:n.reliability,judgement:n.judgement,conflicts:n.conflicts}},scene:{place:PLACES[s.player.location],time:s.time,topic:s.threads?.[id]?.topic||s.scene.topic,openQuestion:s.threads?.[id]?.openQuestion??(s.scene.questionSpeaker===id?s.scene.openQuestion:null),present:present(s).map(k=>({id:k,name:WORLD.npcs[k].name}))},player:{name:s.player.name,age:s.player.age,publicIdentity:'棲風峰弟子，純風靈根'},promises:s.promises.filter(p=>p.to===id).map(p=>({id:p.id,description:p.description,due:p.due,status:!p.knownByRecipient&&(p.kind==='train'||p.status==='missed')?(s.time>p.due?'尚未收到回報':'active'):p.status})),memories:memories.filter(e=>e.knowers?.includes(id)).map(({knowers,...e})=>e),transcript:transcript.filter(m=>m.audience.includes(id)).map(({audience,...m})=>m)};}
export function applyNarrative(s,id,out,allowedIds){if(!out||!Array.isArray(out.lines)||out.lines.length<1||out.lines.length>4)throw Error('AI 回應格式不符，未提交回合');const lines=out.lines.map(line=>{if(!['narrator',id].includes(line.speaker)||typeof line.text!=='string'||!line.text.trim()||line.text.length>500)throw Error('AI 越過敘事範圍，未提交回合');if(/(?:洛河|你)(?:決定|答應|承諾|原諒|愛上|殺死)/.test(line.text))throw Error('AI 代替玩家作出決定，未提交回合');return {speaker:line.speaker,text:line.text.trim()};});if(!lines.some(l=>l.speaker===id))throw Error('AI 沒有提供人物回應');if(!Array.isArray(out.memoryRefs)||out.memoryRefs.some(x=>!allowedIds.includes(x)))throw Error('AI 引用了未知記憶，未提交回合');if(out.openQuestion!==null&&(typeof out.openQuestion!=='string'||out.openQuestion.length>160))throw Error('未回答問題格式錯誤');const audience=['player',...present(s)];for(const l of lines){let event=null;if(l.speaker===id)event=record(s,'npc-speech',`${WORLD.npcs[id].name}說：「${l.text}」`,audience,{assertions:'unverified'},'當面聽見').id;message(s,l.speaker,l.text,l.speaker==='narrator'?'narration':'dialogue',audience,event);}if(out.remember!==undefined){if(!Array.isArray(out.remember)||out.remember.length>3)throw Error('重要記憶格式不符');for(const q of out.remember){const m=s.messages.find(m=>m.speaker==='player'&&m.audience.includes(id)&&typeof q==='string'&&q.length>=2&&q.length<=200&&m.content.includes(q));if(!m)throw Error('重要記憶缺少本回合對話來源');const e=record(s,'personal-memory',`洛河曾說：「${q}」`,m.audience,{message:m.id,assertions:'unverified'},'對話原文');e.links=[m.event].filter(Boolean);}}s.scene.topic=String(out.topic||s.scene.topic).slice(0,120);s.scene.openQuestion=out.openQuestion;s.scene.questionSpeaker=out.openQuestion?id:null;s.threads??={};s.threads[id]={topic:s.scene.topic,openQuestion:out.openQuestion};
const tones=['平靜','關切','警惕','不悅','欣慰','疑惑'];if(tones.includes(out.emotion)){s.npcs[id].emotionalState=out.emotion;s.npcs[id].emotionUntil=s.time+60;}return s;}
export function playerView(s){return {id:s.id,mode:s.mode,revision:s.revision,time:s.time,player:s.player,scene:s.scene,places:PLACES,personality:personalityOf(s),incidentActions:incidentActions(s),locator:Object.entries(s.npcs).map(([id,n])=>({id,name:WORLD.npcs[id].name,location:n.location,travel:n.travel?{...n.travel}:null})),contacts:Object.values(s.contacts),npcs:present(s).map(id=>({id,...WORLD.npcs[id],realm:s.npcs[id].realm})),promises:s.promises,events:s.events.filter(e=>e.knowers.includes('player')).map(({knowers,...e})=>e),messages:s.messages.filter(m=>m.audience.includes('player')).map(({audience,...m})=>m)};}
