-- NEXT PHASE DESIGN ONLY: not a deployed migration.
PRAGMA foreign_keys=ON;
CREATE TABLE rule_packs(id TEXT PRIMARY KEY,version INTEGER NOT NULL,content TEXT NOT NULL,hash TEXT NOT NULL,UNIQUE(id,version));
CREATE TABLE world_templates(id TEXT PRIMARY KEY,version INTEGER NOT NULL,rules_id TEXT NOT NULL REFERENCES rule_packs(id),content TEXT NOT NULL,hash TEXT NOT NULL);
CREATE TABLE npc_templates(id TEXT PRIMARY KEY,world_template_id TEXT NOT NULL REFERENCES world_templates(id),version INTEGER NOT NULL,identity TEXT NOT NULL,personality TEXT NOT NULL,principles TEXT NOT NULL,initial_state TEXT NOT NULL);
CREATE TABLE visual_profiles(id TEXT PRIMARY KEY,npc_template_id TEXT REFERENCES npc_templates(id),version INTEGER NOT NULL,appearance TEXT NOT NULL,reference_asset TEXT);
CREATE TABLE timelines(id TEXT PRIMARY KEY,owner TEXT NOT NULL,template_id TEXT NOT NULL REFERENCES world_templates(id),parent_id TEXT REFERENCES timelines(id),fork_snapshot_id TEXT,world_minute INTEGER NOT NULL,revision INTEGER NOT NULL,schema_version INTEGER NOT NULL,seed TEXT NOT NULL);
CREATE TABLE locations(id TEXT PRIMARY KEY,template_id TEXT NOT NULL REFERENCES world_templates(id),parent_id TEXT REFERENCES locations(id),name TEXT NOT NULL,geometry TEXT NOT NULL,access_rules TEXT NOT NULL);
CREATE TABLE edges(id TEXT PRIMARY KEY,from_id TEXT NOT NULL REFERENCES locations(id),to_id TEXT NOT NULL REFERENCES locations(id),minutes INTEGER NOT NULL CHECK(minutes>0),conditions TEXT NOT NULL,bidirectional INTEGER NOT NULL);
CREATE TABLE factions(id TEXT PRIMARY KEY,template_id TEXT NOT NULL REFERENCES world_templates(id),name TEXT NOT NULL,constitution TEXT NOT NULL);
CREATE TABLE entity_states(timeline_id TEXT NOT NULL REFERENCES timelines(id),entity_id TEXT NOT NULL,template_id TEXT REFERENCES npc_templates(id),location_id TEXT REFERENCES locations(id),alive INTEGER NOT NULL,realm TEXT,stats TEXT NOT NULL,goals TEXT NOT NULL,PRIMARY KEY(timeline_id,entity_id));
CREATE TABLE faction_states(timeline_id TEXT NOT NULL REFERENCES timelines(id),faction_id TEXT NOT NULL REFERENCES factions(id),resources TEXT NOT NULL,plans TEXT NOT NULL,PRIMARY KEY(timeline_id,faction_id));
CREATE TABLE inventory(timeline_id TEXT NOT NULL,entity_id TEXT NOT NULL,item_id TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>=0),PRIMARY KEY(timeline_id,entity_id,item_id),FOREIGN KEY(timeline_id,entity_id) REFERENCES entity_states(timeline_id,entity_id));
CREATE TABLE wallets(timeline_id TEXT NOT NULL,entity_id TEXT NOT NULL,currency TEXT NOT NULL,balance INTEGER NOT NULL CHECK(balance>=0),PRIMARY KEY(timeline_id,entity_id,currency),FOREIGN KEY(timeline_id,entity_id) REFERENCES entity_states(timeline_id,entity_id));
CREATE TABLE injuries(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL,entity_id TEXT NOT NULL,type TEXT NOT NULL,severity INTEGER NOT NULL,onset_minute INTEGER NOT NULL,recovery_rule TEXT NOT NULL,treatment TEXT NOT NULL,FOREIGN KEY(timeline_id,entity_id) REFERENCES entity_states(timeline_id,entity_id));
CREATE TABLE events(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL REFERENCES timelines(id),seq INTEGER NOT NULL,world_minute INTEGER NOT NULL,recorded_at TEXT NOT NULL,type TEXT NOT NULL,location_id TEXT REFERENCES locations(id),objective_content TEXT NOT NULL,source TEXT NOT NULL,truth_status TEXT NOT NULL,effects TEXT NOT NULL,request_id TEXT NOT NULL,UNIQUE(timeline_id,seq));
CREATE INDEX event_time ON events(timeline_id,world_minute,seq);
CREATE TABLE event_entities(event_id TEXT NOT NULL REFERENCES events(id),entity_id TEXT NOT NULL,role TEXT NOT NULL,PRIMARY KEY(event_id,entity_id,role));
CREATE TABLE event_links(source_event_id TEXT NOT NULL REFERENCES events(id),target_event_id TEXT NOT NULL REFERENCES events(id),relation TEXT NOT NULL,PRIMARY KEY(source_event_id,target_event_id,relation));
CREATE TABLE knowledge_claims(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL,actor_id TEXT NOT NULL,event_id TEXT REFERENCES events(id),proposition TEXT NOT NULL,belief_status TEXT NOT NULL,confidence REAL NOT NULL CHECK(confidence>=0 AND confidence<=1),acquired_minute INTEGER NOT NULL,supersedes_id TEXT REFERENCES knowledge_claims(id),FOREIGN KEY(timeline_id,actor_id) REFERENCES entity_states(timeline_id,entity_id));
CREATE INDEX actor_knowledge ON knowledge_claims(timeline_id,actor_id,acquired_minute);
CREATE TABLE knowledge_sources(id TEXT PRIMARY KEY,claim_id TEXT NOT NULL REFERENCES knowledge_claims(id),source_actor_id TEXT,channel TEXT NOT NULL,source_event_id TEXT REFERENCES events(id),credibility REAL NOT NULL);
CREATE TABLE transmissions(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL REFERENCES timelines(id),sender TEXT NOT NULL,receiver TEXT NOT NULL,claim_id TEXT NOT NULL REFERENCES knowledge_claims(id),channel TEXT NOT NULL,sent_minute INTEGER NOT NULL,received_minute INTEGER,status TEXT NOT NULL);
CREATE TABLE relationships(timeline_id TEXT NOT NULL,from_actor TEXT NOT NULL,to_actor TEXT NOT NULL,trust REAL NOT NULL,respect REAL NOT NULL,closeness REAL NOT NULL,caution REAL NOT NULL,alignment REAL NOT NULL,dependence REAL NOT NULL,PRIMARY KEY(timeline_id,from_actor,to_actor),FOREIGN KEY(timeline_id,from_actor) REFERENCES entity_states(timeline_id,entity_id),FOREIGN KEY(timeline_id,to_actor) REFERENCES entity_states(timeline_id,entity_id));
CREATE TABLE relationship_events(timeline_id TEXT NOT NULL,from_actor TEXT NOT NULL,to_actor TEXT NOT NULL,event_id TEXT NOT NULL REFERENCES events(id),unresolved INTEGER NOT NULL,PRIMARY KEY(timeline_id,from_actor,to_actor,event_id),FOREIGN KEY(timeline_id,from_actor,to_actor) REFERENCES relationships(timeline_id,from_actor,to_actor));
CREATE TABLE commitments(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL REFERENCES timelines(id),maker TEXT NOT NULL,recipient TEXT NOT NULL,created_event_id TEXT NOT NULL REFERENCES events(id),terms TEXT NOT NULL,due_minute INTEGER,status TEXT NOT NULL,resolved_event_id TEXT REFERENCES events(id));
CREATE TABLE truths(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL REFERENCES timelines(id),sealed_at TEXT NOT NULL,sealed_hash TEXT NOT NULL,past_and_mechanism TEXT NOT NULL,participants_motives_resources TEXT NOT NULL,original_timeline TEXT NOT NULL,evidence_manifest TEXT NOT NULL,faction_knowledge TEXT NOT NULL,no_player_outcome TEXT NOT NULL,modifiable_nodes TEXT NOT NULL,ending_constraints TEXT NOT NULL);
CREATE TRIGGER truths_no_update BEFORE UPDATE ON truths BEGIN SELECT RAISE(ABORT,'sealed truth immutable'); END;
CREATE TRIGGER truths_no_delete BEFORE DELETE ON truths BEGIN SELECT RAISE(ABORT,'sealed truth immutable'); END;
CREATE TABLE plot_states(timeline_id TEXT NOT NULL,truth_id TEXT NOT NULL REFERENCES truths(id),phase TEXT NOT NULL,future_plan TEXT NOT NULL,actual_outcome TEXT,PRIMARY KEY(timeline_id,truth_id));
CREATE TABLE evidence(id TEXT PRIMARY KEY,truth_id TEXT NOT NULL REFERENCES truths(id),timeline_id TEXT NOT NULL REFERENCES timelines(id),location_id TEXT REFERENCES locations(id),holder_id TEXT,objective_data TEXT NOT NULL,misleading_source TEXT,first_revealed_event_id TEXT REFERENCES events(id));
CREATE TABLE scheduled_jobs(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL REFERENCES timelines(id),due_minute INTEGER NOT NULL,priority INTEGER NOT NULL,sequence INTEGER NOT NULL,kind TEXT NOT NULL,payload TEXT NOT NULL,conditions TEXT NOT NULL,interrupt_policy TEXT NOT NULL,status TEXT NOT NULL);
CREATE INDEX job_due ON scheduled_jobs(timeline_id,status,due_minute,priority,sequence);
CREATE TABLE journeys(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL,entity_id TEXT NOT NULL,from_location TEXT NOT NULL REFERENCES locations(id),to_location TEXT NOT NULL REFERENCES locations(id),depart_minute INTEGER NOT NULL,arrive_minute INTEGER NOT NULL,route TEXT NOT NULL,status TEXT NOT NULL,FOREIGN KEY(timeline_id,entity_id) REFERENCES entity_states(timeline_id,entity_id));
CREATE TABLE snapshots(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL REFERENCES timelines(id),revision INTEGER NOT NULL,world_minute INTEGER NOT NULL,schema_version INTEGER NOT NULL,content TEXT NOT NULL,content_hash TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE turn_commits(timeline_id TEXT NOT NULL REFERENCES timelines(id),request_id TEXT NOT NULL,input_hash TEXT NOT NULL,base_revision INTEGER NOT NULL,committed_revision INTEGER NOT NULL,result TEXT NOT NULL,PRIMARY KEY(timeline_id,request_id));
CREATE TABLE narrative_outbox(id TEXT PRIMARY KEY,timeline_id TEXT NOT NULL REFERENCES timelines(id),request_id TEXT NOT NULL,visible_context TEXT NOT NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL,result TEXT);
CREATE TABLE assets(id TEXT PRIMARY KEY,kind TEXT NOT NULL,profile_id TEXT REFERENCES visual_profiles(id),pose TEXT,expression TEXT,style_version INTEGER NOT NULL,uri TEXT NOT NULL,content_hash TEXT NOT NULL);
CREATE TABLE memory_embeddings(claim_id TEXT NOT NULL REFERENCES knowledge_claims(id),model_version TEXT NOT NULL,external_index_id TEXT NOT NULL,PRIMARY KEY(claim_id,model_version));
CREATE TABLE known_locations(timeline_id TEXT NOT NULL,actor_id TEXT NOT NULL,location_id TEXT NOT NULL REFERENCES locations(id),source_event_id TEXT NOT NULL REFERENCES events(id),PRIMARY KEY(timeline_id,actor_id,location_id),FOREIGN KEY(timeline_id,actor_id) REFERENCES entity_states(timeline_id,entity_id));
CREATE TRIGGER events_no_update BEFORE UPDATE ON events BEGIN SELECT RAISE(ABORT,'objective history immutable'); END;
CREATE TRIGGER events_no_delete BEFORE DELETE ON events BEGIN SELECT RAISE(ABORT,'objective history immutable'); END;
-- Application validation must also enforce that references (event/claim/evidence/commit)
-- share timeline_id. A simple FK on global IDs alone does not enforce branch isolation.
-- Production migration should use composite UNIQUE(timeline_id,id) references before rollout.
